# GitHub 赞助配置
# 这将在项目页面显示"Sponsor"按钮

# 爱发电（推荐国内用户）
custom: ['https://afdian.com/a/miaotouy']

# 如果之后开通 GitHub Sponsors，取消下面的注释
# github: [miaotouy]

# 其他平台示例（按需添加）
# patreon: username
# ko_fi: username
# open_collective: project-name