/**
 * Anthropic (Claude) 系列模型前缀匹配规则
 */
import type { ModelMetadataRule } from "../../types/model-metadata";

// ===============================
// Claude 模型的能力配置模板
// ===============================

const claudeBaseCapabilities = {
  vision: true,
  toolUse: true,
  document: true,
  documentFormat: "base64" as const,
  visionTokenCost: {
    calculationMethod: "claude_3" as const,
    parameters: {
      costPerImage: 1000, // 预估值，实际由 API 返回
    },
  },
  documentTokenCost: {
    calculationMethod: "dynamic" as const, // Claude API 会返回实际 token 消耗
  },
};

const claudeExtendedThinkingCapabilities = {
  ...claudeBaseCapabilities,
  thinking: true,
  thinkingConfigType: "budget" as const,
};

const claudeAdaptiveThinkingCapabilities = {
  ...claudeBaseCapabilities,
  thinking: false,
  thinkingConfigType: "none" as const,
};

export const anthropicModelRules: ModelMetadataRule[] = [
  // === Claude 当前具体模型信息（官方模型页/价格页，2026-05） ===
  {
    id: "model-claude-opus-4-8",
    matchType: "modelPrefix",
    matchValue: "claude-opus-4-8",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude Opus 4",
      tokenizer: "claude",
      contextLength: 1000000,
      maxOutputTokens: 128000,
      pricing: {
        input: 5.0,
        output: 25.0,
        cacheHitInput: 0.5,
        unit: "USD",
        note: "每百万 token；Cache Hits & Refreshes 为 $0.50/MTok",
      },
      capabilities: claudeAdaptiveThinkingCapabilities,
      adaptiveThinking: true,
      releaseDate: "2026-05-28",
      knowledgeCutoff: "2026-01",
      trainingDataCutoff: "2026-01",
      notBeforeRetirementDate: "2027-05-28",
      description:
        "Claude Opus 4.8：Anthropic 最强复杂推理与长程 agentic coding 模型，1M 上下文，128K 输出，支持自适应思考",
    },
    priority: 36,
    enabled: true,
    description: "模型前缀 claude-opus-4-8 元数据规则",
  },
  {
    id: "model-claude-opus-4-7",
    matchType: "modelPrefix",
    matchValue: "claude-opus-4-7",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude Opus 4",
      tokenizer: "claude",
      contextLength: 1000000,
      maxOutputTokens: 128000,
      pricing: {
        input: 5.0,
        output: 25.0,
        cacheHitInput: 0.5,
        unit: "USD",
        note: "每百万 token；Cache Hits & Refreshes 为 $0.50/MTok",
      },
      capabilities: claudeAdaptiveThinkingCapabilities,
      adaptiveThinking: true,
      releaseDate: "2026-04-16",
      knowledgeCutoff: "2026-01",
      trainingDataCutoff: "2026-01",
      notBeforeRetirementDate: "2027-04-16",
      description:
        "Claude Opus 4.7：1M 上下文、128K 输出的 Opus 4 高能力模型，支持自适应思考",
    },
    priority: 36,
    enabled: true,
    description: "模型前缀 claude-opus-4-7 元数据规则",
  },
  {
    id: "model-claude-opus-4-6",
    matchType: "modelPrefix",
    matchValue: "claude-opus-4-6",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude Opus 4",
      tokenizer: "claude",
      contextLength: 1000000,
      maxOutputTokens: 128000,
      pricing: {
        input: 5.0,
        output: 25.0,
        cacheHitInput: 0.5,
        unit: "USD",
        note: "每百万 token；Cache Hits & Refreshes 为 $0.50/MTok",
      },
      capabilities: claudeExtendedThinkingCapabilities,
      adaptiveThinking: true,
      releaseDate: "2026-02-05",
      knowledgeCutoff: "2025-05",
      trainingDataCutoff: "2025-08",
      notBeforeRetirementDate: "2027-02-05",
      description:
        "Claude Opus 4.6：1M 上下文、128K 输出的 Opus 4 模型，支持扩展思考与自适应思考",
    },
    priority: 36,
    enabled: true,
    description: "模型前缀 claude-opus-4-6 元数据规则",
  },
  {
    id: "model-claude-sonnet-4-6",
    matchType: "modelPrefix",
    matchValue: "claude-sonnet-4-6",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude Sonnet 4",
      tokenizer: "claude",
      contextLength: 1000000,
      maxOutputTokens: 64000,
      pricing: {
        input: 3.0,
        output: 15.0,
        cacheHitInput: 0.3,
        unit: "USD",
        note: "每百万 token；Cache Hits & Refreshes 为 $0.30/MTok",
      },
      capabilities: claudeExtendedThinkingCapabilities,
      adaptiveThinking: true,
      releaseDate: "2026-02-17",
      knowledgeCutoff: "2025-08",
      trainingDataCutoff: "2026-01",
      notBeforeRetirementDate: "2027-02-17",
      description:
        "Claude Sonnet 4.6：速度与智能均衡的主力模型，1M 上下文，64K 输出，支持扩展思考与自适应思考",
    },
    priority: 36,
    enabled: true,
    description: "模型前缀 claude-sonnet-4-6 元数据规则",
  },
  {
    id: "model-claude-haiku-4-5",
    matchType: "modelPrefix",
    matchValue: "claude-haiku-4-5",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude Haiku 4.5",
      tokenizer: "claude",
      contextLength: 200000,
      maxOutputTokens: 64000,
      pricing: {
        input: 1.0,
        output: 5.0,
        cacheHitInput: 0.1,
        unit: "USD",
        note: "每百万 token；Cache Hits & Refreshes 为 $0.10/MTok",
      },
      capabilities: claudeExtendedThinkingCapabilities,
      releaseDate: "2025-10-01",
      knowledgeCutoff: "2025-02",
      trainingDataCutoff: "2025-07",
      notBeforeRetirementDate: "2026-10-15",
      description:
        "Claude Haiku 4.5：最快的近前沿 Claude 模型，200K 上下文，64K 输出，支持扩展思考",
    },
    priority: 36,
    enabled: true,
    description: "模型前缀 claude-haiku-4-5 元数据规则",
  },
  {
    id: "model-claude-sonnet-4-5",
    matchType: "modelPrefix",
    matchValue: "claude-sonnet-4-5",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude Sonnet 4",
      tokenizer: "claude",
      contextLength: 200000,
      maxOutputTokens: 64000,
      pricing: {
        input: 3.0,
        output: 15.0,
        cacheHitInput: 0.3,
        unit: "USD",
        note: "每百万 token；Cache Hits & Refreshes 为 $0.30/MTok",
      },
      capabilities: claudeExtendedThinkingCapabilities,
      releaseDate: "2025-09-29",
      knowledgeCutoff: "2025-01",
      trainingDataCutoff: "2025-07",
      notBeforeRetirementDate: "2026-09-29",
      description:
        "Claude Sonnet 4.5：上一代 Sonnet 4 高能力模型，200K 上下文，64K 输出，支持扩展思考",
    },
    priority: 36,
    enabled: true,
    description: "模型前缀 claude-sonnet-4-5 元数据规则",
  },
  {
    id: "model-claude-opus-4-5",
    matchType: "modelPrefix",
    matchValue: "claude-opus-4-5",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude Opus 4",
      tokenizer: "claude",
      contextLength: 200000,
      maxOutputTokens: 64000,
      pricing: {
        input: 5.0,
        output: 25.0,
        cacheHitInput: 0.5,
        unit: "USD",
        note: "每百万 token；Cache Hits & Refreshes 为 $0.50/MTok",
      },
      capabilities: claudeExtendedThinkingCapabilities,
      releaseDate: "2025-11-01",
      knowledgeCutoff: "2025-05",
      trainingDataCutoff: "2025-08",
      notBeforeRetirementDate: "2026-11-24",
      description:
        "Claude Opus 4.5：Opus 4 高能力模型，200K 上下文，64K 输出，支持扩展思考",
    },
    priority: 36,
    enabled: true,
    description: "模型前缀 claude-opus-4-5 元数据规则",
  },
  {
    id: "model-claude-opus-4-1",
    matchType: "modelPrefix",
    matchValue: "claude-opus-4-1",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude Opus 4",
      tokenizer: "claude",
      contextLength: 200000,
      maxOutputTokens: 32000,
      pricing: {
        input: 15.0,
        output: 75.0,
        cacheHitInput: 1.5,
        unit: "USD",
        note: "每百万 token；Cache Hits & Refreshes 为 $1.50/MTok",
      },
      capabilities: claudeExtendedThinkingCapabilities,
      releaseDate: "2025-08-05",
      knowledgeCutoff: "2025-01",
      trainingDataCutoff: "2025-03",
      notBeforeRetirementDate: "2026-08-05",
      description:
        "Claude Opus 4.1：Opus 4 高能力模型，200K 上下文，32K 输出，支持扩展思考",
    },
    priority: 36,
    enabled: true,
    description: "模型前缀 claude-opus-4-1 元数据规则",
  },
  {
    id: "model-claude-sonnet-4-20250514",
    matchType: "modelPrefix",
    matchValue: "claude-sonnet-4-20250514",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude Sonnet 4",
      tokenizer: "claude",
      contextLength: 200000,
      maxOutputTokens: 64000,
      pricing: {
        input: 3.0,
        output: 15.0,
        cacheHitInput: 0.3,
        unit: "USD",
        note: "每百万 token；Cache Hits & Refreshes 为 $0.30/MTok",
      },
      capabilities: claudeExtendedThinkingCapabilities,
      releaseDate: "2025-05-14",
      knowledgeCutoff: "2025-01",
      trainingDataCutoff: "2025-03",
      deprecated: true,
      deprecationDate: "2026-04-14",
      retirementDate: "2026-06-15",
      description:
        "Claude Sonnet 4 初版模型（已废弃，将于 2026-06-15 退役；建议迁移到 Sonnet 4.6）",
    },
    priority: 36,
    enabled: true,
    description: "模型前缀 claude-sonnet-4-20250514 元数据规则",
  },
  {
    id: "model-claude-opus-4-20250514",
    matchType: "modelPrefix",
    matchValue: "claude-opus-4-20250514",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude Opus 4",
      tokenizer: "claude",
      contextLength: 200000,
      maxOutputTokens: 32000,
      pricing: {
        input: 15.0,
        output: 75.0,
        cacheHitInput: 1.5,
        unit: "USD",
        note: "每百万 token；Cache Hits & Refreshes 为 $1.50/MTok",
      },
      capabilities: claudeExtendedThinkingCapabilities,
      releaseDate: "2025-05-14",
      knowledgeCutoff: "2025-01",
      trainingDataCutoff: "2025-03",
      deprecated: true,
      deprecationDate: "2026-04-14",
      retirementDate: "2026-06-15",
      description:
        "Claude Opus 4 初版模型（已废弃，将于 2026-06-15 退役；建议迁移到 Opus 4.8）",
    },
    priority: 36,
    enabled: true,
    description: "模型前缀 claude-opus-4-20250514 元数据规则",
  },
  {
    id: "model-prefix-claude-4",
    matchType: "modelPrefix",
    matchValue: "claude-(?:opus|sonnet|haiku)-4",
    useRegex: true,
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude 4",
      tokenizer: "claude",
      capabilities: claudeExtendedThinkingCapabilities,
      description:
        "Claude 4 系列模型（Opus / Sonnet / Haiku，支持视觉、工具调用、文档处理；多数 4.x 模型支持扩展思考）",
    },
    priority: 25,
    enabled: true,
    description: "模型正则 claude-(?:opus|sonnet|haiku)-4 元数据规则",
  },
  {
    id: "model-prefix-claude-3-7",
    matchType: "modelPrefix",
    matchValue: "claude-3-7",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude 3.7",
      tokenizer: "claude",
      capabilities: claudeExtendedThinkingCapabilities,
      deprecated: true,
      deprecationDate: "2025-10-28",
      retirementDate: "2026-02-19",
      description: "Claude 3.7 Sonnet（已退役，原生支持视觉与扩展思考）",
    },
    priority: 25,
    enabled: true,
    description: "模型前缀 claude-3-7 元数据规则",
  },
  {
    id: "model-prefix-claude-3-5",
    matchType: "modelPrefix",
    matchValue: "claude-3-5",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude 3.5",
      tokenizer: "claude",
      capabilities: claudeBaseCapabilities,
      deprecated: true,
      retirementDate: "2026-02-19",
      description: "Claude 3.5 系列模型（已退役）",
    },
    priority: 25,
    enabled: true,
    description: "模型前缀 claude-3-5 元数据规则",
  },
  {
    id: "model-prefix-claude-3",
    matchType: "modelPrefix",
    matchValue: "claude-3-",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude 3",
      tokenizer: "claude",
      capabilities: claudeBaseCapabilities,
      deprecated: true,
      description: "Claude 3 系列旧模型（多数已退役）",
    },
    priority: 20,
    enabled: true,
    description: "模型前缀 claude-3- 元数据规则",
  },
  {
    id: "model-prefix-claude",
    matchType: "modelPrefix",
    matchValue: "claude-",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude",
      tokenizer: "claude", // Claude 系列使用专用分词器
      capabilities: claudeExtendedThinkingCapabilities,
      description: "Claude 系列模型（支持视觉、工具调用和文档处理）",
    },
    priority: 20,
    enabled: true,
    description: "模型前缀 claude- 元数据规则",
  },
];

