/**
 * Provider 级别匹配规则 (优先级 10)
 *
 * 根据 LLM 服务提供商标识匹配图标和分组。
 */
import type { ModelMetadataRule } from "../../types/model-metadata";

export const providerRules: ModelMetadataRule[] = [
  // === 主流国际 AI 服务商 ===
  {
    id: "provider-openai",
    matchType: "provider",
    matchValue: "openai",
    properties: {
      icon: `/model-icons/openai.svg`,
      group: "OpenAI",
    },
    priority: 10,
    enabled: true,
    description: "OpenAI 提供商图标",
  },
  {
    id: "provider-openai-responses",
    matchType: "provider",
    matchValue: "openai-responses",
    properties: {
      icon: `/model-icons/openai.svg`,
      group: "OpenAI Responses",
    },
    priority: 10,
    enabled: true,
    description: "OpenAI Responses 提供商图标",
  },
  {
    id: "provider-anthropic",
    matchType: "provider",
    matchValue: "anthropic",
    properties: {
      icon: `/model-icons/claude-color.svg`,
      group: "Claude",
    },
    priority: 10,
    enabled: true,
    description: "Anthropic (Claude) 提供商图标",
  },
  {
    id: "provider-google",
    matchType: "provider",
    matchValue: "google",
    properties: {
      icon: `/model-icons/gemini-color.svg`,
      group: "Gemini",
    },
    priority: 10,
    enabled: true,
    description: "Google 提供商图标",
  },
  {
    id: "provider-gemini",
    matchType: "provider",
    matchValue: "gemini",
    properties: {
      icon: `/model-icons/gemini-color.svg`,
      group: "Gemini",
    },
    priority: 10,
    enabled: true,
    description: "Google Gemini 提供商图标",
  },
  {
    id: "provider-cohere",
    matchType: "provider",
    matchValue: "cohere",
    properties: {
      icon: `/model-icons/cohere-color.svg`,
      group: "Cohere",
    },
    priority: 10,
    enabled: true,
    description: "Cohere 提供商图标",
  },
  {
    id: "provider-mistral",
    matchType: "provider",
    matchValue: "mistral",
    properties: {
      icon: `/model-icons/mistral-color.svg`,
      group: "Mistral",
    },
    priority: 10,
    enabled: true,
    description: "Mistral AI 提供商图标",
  },
  {
    id: "provider-meta",
    matchType: "provider",
    matchValue: "meta",
    properties: {
      icon: `/model-icons/meta-color.svg`,
      group: "Meta",
    },
    priority: 10,
    enabled: true,
    description: "Meta 提供商图标",
  },
  {
    id: "provider-microsoft",
    matchType: "provider",
    matchValue: "microsoft",
    properties: {
      icon: `/model-icons/microsoft-color.svg`,
      group: "Microsoft",
    },
    priority: 10,
    enabled: true,
    description: "Microsoft 提供商图标",
  },
  {
    id: "provider-xai",
    matchType: "provider",
    matchValue: "xai",
    properties: {
      icon: `/model-icons/xai.svg`,
      group: "xAI",
    },
    priority: 10,
    enabled: true,
    description: "xAI 提供商图标",
  },
  {
    id: "provider-groq",
    matchType: "provider",
    matchValue: "groq",
    properties: {
      icon: `/model-icons/groq.svg`,
      group: "Groq",
    },
    priority: 10,
    enabled: true,
    description: "Groq 提供商图标",
  },
  {
    id: "provider-ai21",
    matchType: "provider",
    matchValue: "ai21",
    properties: {
      icon: `/model-icons/aionlabs-color.svg`,
      group: "AI21",
    },
    priority: 10,
    enabled: true,
    description: "AI21 Labs 提供商图标",
  },

  // === 国内 AI 服务商 ===
  {
    id: "provider-deepseek",
    matchType: "provider",
    matchValue: "deepseek",
    properties: {
      icon: `/model-icons/deepseek-color.svg`,
      group: "DeepSeek",
    },
    priority: 10,
    enabled: true,
    description: "DeepSeek 提供商图标",
  },
  {
    id: "provider-moonshot",
    matchType: "provider",
    matchValue: "moonshot",
    properties: {
      icon: `/model-icons/kimi-color.svg`,
      group: "Kimi",
    },
    priority: 10,
    enabled: true,
    description: "Moonshot AI (Kimi) 提供商图标",
  },
  {
    id: "provider-zhipu",
    matchType: "provider",
    matchValue: "zhipu",
    properties: {
      icon: `/model-icons/zhipu-color.svg`,
      group: "Zhipu",
    },
    priority: 10,
    enabled: true,
    description: "智谱 AI 提供商图标",
  },
  {
    id: "provider-qwen",
    matchType: "provider",
    matchValue: "qwen",
    properties: {
      icon: `/model-icons/qwen-color.svg`,
      group: "Qwen",
    },
    priority: 10,
    enabled: true,
    description: "通义千问提供商图标",
  },
  {
    id: "provider-alibaba",
    matchType: "provider",
    matchValue: "alibaba",
    properties: {
      icon: `/model-icons/alibaba.svg`,
      group: "Alibaba",
    },
    priority: 10,
    enabled: true,
    description: "阿里巴巴提供商图标",
  },
  {
    id: "provider-bytedance",
    matchType: "provider",
    matchValue: "bytedance",
    properties: {
      icon: `/model-icons/bytedance-color.svg`,
      group: "ByteDance",
    },
    priority: 10,
    enabled: true,
    description: "字节跳动提供商图标",
  },
  {
    id: "provider-baidu",
    matchType: "provider",
    matchValue: "baidu",
    properties: {
      icon: `/model-icons/wenxin-color.svg`,
      group: "Baidu",
    },
    priority: 10,
    enabled: true,
    description: "百度提供商图标",
  },
  {
    id: "provider-tencent",
    matchType: "provider",
    matchValue: "tencent",
    properties: {
      icon: `/model-icons/hunyuan-color.svg`,
      group: "Tencent",
    },
    priority: 10,
    enabled: true,
    description: "腾讯提供商图标",
  },
  {
    id: "provider-minimax",
    matchType: "provider",
    matchValue: "minimax",
    properties: {
      icon: `/model-icons/minimax-color.svg`,
      group: "MiniMax",
    },
    priority: 10,
    enabled: true,
    description: "MiniMax 提供商图标",
  },
  {
    id: "provider-xiaomi",
    matchType: "provider",
    matchValue: "xiaomi",
    properties: {
      icon: `/model-icons/xiaomimimo.svg`,
      group: "Xiaomi",
    },
    priority: 10,
    enabled: true,
    description: "小米提供商图标",
  },
  {
    id: "provider-kunlun",
    matchType: "provider",
    matchValue: "kunlun",
    properties: {
      icon: `/model-icons/skyreels.svg`,
      group: "Kunlun",
    },
    priority: 10,
    enabled: true,
    description: "昆仑万维提供商图标",
  },
  {
    id: "provider-shengshu",
    matchType: "provider",
    matchValue: "shengshu",
    properties: {
      icon: `/model-icons/vidu.svg`,
      group: "ShengShu",
    },
    priority: 10,
    enabled: true,
    description: "生数科技提供商图标",
  },
  {
    id: "provider-01ai",
    matchType: "provider",
    matchValue: "01ai",
    properties: {
      icon: `/model-icons/yi-color.svg`,
      group: "Yi",
    },
    priority: 10,
    enabled: true,
    description: "零一万物提供商图标",
  },
  {
    id: "provider-baichuan",
    matchType: "provider",
    matchValue: "baichuan",
    properties: {
      icon: `/model-icons/baichuan-color.svg`,
      group: "Baichuan",
    },
    priority: 10,
    enabled: true,
    description: "百川提供商图标",
  },
  {
    id: "provider-sensenova",
    matchType: "provider",
    matchValue: "sensenova",
    properties: {
      icon: `/model-icons/sensenova-color.svg`,
      group: "SenseNova",
    },
    priority: 10,
    enabled: true,
    description: "商汤提供商图标",
  },
  {
    id: "provider-kwai",
    matchType: "provider",
    matchValue: "kwai-kolors|kwaipilot",
    useRegex: true,
    properties: {
      icon: `/model-icons/kolors-color.svg`,
      group: "Kwai",
    },
    priority: 10,
    enabled: true,
    description: "快手 Kolors 提供商图标",
  },
  {
    id: "provider-siliconflow",
    matchType: "provider",
    matchValue: "siliconflow",
    properties: {
      icon: `/model-icons/siliconcloud-color.svg`,
      group: "SiliconFlow",
    },
    priority: 10,
    enabled: true,
    description: "SiliconFlow 提供商图标",
  },
  {
    id: "provider-inclusionai",
    matchType: "provider",
    matchValue: "inclusionai",
    properties: {
      icon: `/model-icons/ling.png`,
      group: "InclusionAI",
    },
    priority: 10,
    enabled: true,
    description: "蚂蚁集团旗下 Inclusion AI 提供商图标",
  },
  {
    id: "provider-agnes-ai",
    matchType: "provider",
    matchValue: "agnes|agnes-ai|sapiens|sapiens-ai",
    useRegex: true,
    properties: {
      icon: `/model-icons/agnes.png`,
      group: "Agnes AI",
    },
    priority: 10,
    enabled: true,
    description: "Agnes AI / Sapiens AI 提供商图标",
  },
  {
    id: "provider-wan-ai",
    matchType: "provider",
    matchValue: "wan-ai",
    properties: {
      icon: `/model-icons/qwen-color.svg`,
      group: "Qwen",
    },
    priority: 10,
    enabled: true,
    description: "千问万象 (Wan AI) 提供商图标",
  },
  {
    id: "provider-stepfun-ai",
    matchType: "provider",
    matchValue: "stepfun-ai",
    properties: {
      icon: `/model-icons/stepfun-color.svg`,
      group: "StepFun",
    },
    priority: 10,
    enabled: true,
    description: "StepFun AI 提供商图标",
  },
  {
    id: "provider-teleai",
    matchType: "provider",
    matchValue: "teleai",
    properties: {
      icon: `/model-icons/TeleAI.svg`,
      group: "TeleAI",
    },
    priority: 10,
    enabled: true,
    description: "TeleAI 提供商图标",
  },
  {
    id: "provider-ascend-tribe",
    matchType: "provider",
    matchValue: "ascend-tribe",
    properties: {
      icon: `/model-icons/ascend_tribe.png`,
      group: "Pangu",
    },
    priority: 10,
    enabled: true,
    description: "Ascend Tribe (Pangu) 提供商图标",
  },
  {
    id: "provider-fnlp",
    matchType: "provider",
    matchValue: "fnlp",
    properties: {
      icon: `/model-icons/openmoss.svg`,
      group: "MOSS",
    },
    priority: 10,
    enabled: true,
    description: "MOSS (FNLP) 提供商图标",
  },
  {
    id: "provider-funaudiollm",
    matchType: "provider",
    matchValue: "funaudiollm",
    properties: {
      icon: `/model-icons/FunAudioLLM.png`,
      group: "FunAudioLLM",
    },
    priority: 10,
    enabled: true,
    description: "FunAudioLLM 提供商图标",
  },
  {
    id: "provider-indexteam",
    matchType: "provider",
    matchValue: "indexteam",
    properties: {
      icon: `/model-icons/IndexTeam.svg`,
      group: "IndexTeam",
    },
    priority: 10,
    enabled: true,
    description: "IndexTeam 提供商图标",
  },
  {
    id: "provider-netease-youdao",
    matchType: "provider",
    matchValue: "netease-youdao",
    properties: {
      icon: `/model-icons/netease-youdao.svg`,
      group: "Netease Youdao",
    },
    priority: 10,
    enabled: true,
    description: "网易有道提供商图标",
  },
  {
    id: "provider-fishaudio",
    matchType: "provider",
    matchValue: "fishaudio",
    properties: {
      icon: `/model-icons/fishaudio.svg`,
      group: "FishAudio",
    },
    priority: 10,
    enabled: true,
    description: "FishAudio 提供商图标",
  },

  // === 其他服务商 ===
  {
    id: "provider-huggingface",
    matchType: "provider",
    matchValue: "huggingface",
    properties: {
      icon: `/model-icons/huggingface-color.svg`,
      group: "HuggingFace",
    },
    priority: 10,
    enabled: true,
    description: "HuggingFace 提供商图标",
  },
  {
    id: "provider-z-ai",
    matchType: "provider",
    matchValue: "z-ai",
    properties: {
      icon: `/model-icons/zai.svg`,
      group: "Z AI",
    },
    priority: 10,
    enabled: true,
    description: "Z AI 提供商图标",
  },
  {
    id: "provider-nebius",
    matchType: "provider",
    matchValue: "nebius",
    properties: {
      icon: `/model-icons/nebius.svg`,
      group: "Nebius",
    },
    priority: 10,
    enabled: true,
    description: "Nebius 提供商图标",
  },
  {
    id: "provider-stabilityai",
    matchType: "provider",
    matchValue: "stabilityai",
    properties: {
      icon: `/model-icons/stability-color.svg`,
      group: "Stability AI",
    },
    priority: 10,
    enabled: true,
    description: "Stability AI 提供商图标",
  },
  {
    id: "provider-baai",
    matchType: "provider",
    matchValue: "baai",
    properties: {
      icon: `/model-icons/baai.svg`,
      group: "BAAI",
    },
    priority: 10,
    enabled: true,
    description: "智源研究院 BAAI 提供商图标",
  },
  {
    id: "provider-black-forest-labs",
    matchType: "provider",
    matchValue: "black-forest-labs",
    properties: {
      icon: `/model-icons/flux.svg`,
      group: "Black Forest Labs",
    },
    priority: 10,
    enabled: true,
    description: "Black Forest Labs 提供商图标",
  },
  {
    id: "model-prefix-nemotron",
    matchType: "modelPrefix",
    matchValue: "nemotron",
    properties: {
      icon: `/model-icons/nvidia-color.svg`,
      group: "NVIDIA",
    },
    priority: 20,
    enabled: true,
    description: "Nemotron 系列模型图标",
  },
  {
    id: "provider-nvidia",
    matchType: "provider",
    matchValue: "nvidia",
    properties: {
      icon: `/model-icons/nvidia-color.svg`,
      group: "NVIDIA",
    },
    priority: 10,
    enabled: true,
    description: "NVIDIA 提供商图标",
  },
  {
    id: "provider-meituan",
    matchType: "provider",
    matchValue: "meituan",
    properties: {
      icon: `/model-icons/longcat-color.svg`,
      group: "Meituan",
    },
    priority: 10,
    enabled: true,
    description: "美团提供商图标",
  },
  {
    id: "model-prefix-longcat",
    matchType: "modelPrefix",
    matchValue: "longcat",
    properties: {
      icon: `/model-icons/longcat-color.svg`,
      group: "Meituan",
    },
    priority: 20,
    enabled: true,
    description: "美团 Longcat 系列模型图标",
  },

  // === API 服务商 ===
  {
    id: "provider-openrouter",
    matchType: "provider",
    matchValue: "openrouter",
    properties: {
      icon: `/model-icons/openrouter.svg`,
      group: "OpenRouter",
    },
    priority: 10,
    enabled: true,
    description: "OpenRouter 提供商图标",
  },
  {
    id: "model-prefix-openrouter",
    matchType: "modelPrefix",
    matchValue: "openrouter",
    properties: {
      icon: `/model-icons/openrouter.svg`,
      group: "OpenRouter",
    },
    priority: 20,
    enabled: true,
    description: "OpenRouter 模型区匹配图标",
  },
];
