/**
 * LLM 服务商预设模板配置
 */

import type { ProviderType, LlmModelInfo, LlmLink } from "../types/llm-profiles";

/**
 * 预设模板接口
 */
export interface LlmPreset {
  type: ProviderType;
  name: string;
  description: string;
  defaultBaseUrl: string;
  logoUrl?: string;
  defaultModels?: LlmModelInfo[];
  links?: LlmLink[];
}

/**
 * LLM 服务商预设模板列表
 * 用于快速创建常用服务配置
 */
export const llmPresets: LlmPreset[] = [
  // VCP (Variable & Command Protocol)
  {
    type: "openai",
    name: "VCP",
    description: "VCP server - VCP 服务 (OpenAI 兼容)",
    defaultBaseUrl: "http://localhost:6505",
    logoUrl: "/model-icons/vcpchat.png",
    links: [{ label: "GitHub", url: "https://github.com/lioensky/VCPToolBox" }],
  },
  // DeepSeek
  {
    type: "deepseek",
    name: "DeepSeek",
    description: "深度求索 API",
    defaultBaseUrl: "https://api.deepseek.com",
    logoUrl: "/model-icons/deepseek-color.svg",
    links: [
      { label: "官网", url: "https://www.deepseek.com" },
      { label: "API 文档", url: "https://api-docs.deepseek.com" },
      { label: "计费说明", url: "https://api-docs.deepseek.com/zh-cn/quick_start/pricing" },
    ],
    defaultModels: [
      {
        id: "deepseek-reasoner",
        name: "DeepSeek Reasoner",
        group: "DeepSeek",
        provider: "deepseek",
        capabilities: { toolUse: true, thinking: true, thinkingConfigType: "switch" },
        description: "推理专用模型",
      },
      {
        id: "deepseek-chat",
        name: "DeepSeek Chat",
        group: "DeepSeek",
        provider: "deepseek",
        capabilities: { toolUse: true, thinking: true, thinkingConfigType: "switch" },
        description: "通用对话模型",
      },
    ],
  },
  // OpenAI 官方
  {
    type: "openai",
    name: "OpenAI",
    description: "OpenAI 官方服务",
    defaultBaseUrl: "https://api.openai.com",
    logoUrl: "/model-icons/openai.svg",
    links: [
      { label: "控制台", url: "https://platform.openai.com" },
      { label: "API 文档", url: "https://platform.openai.com/docs/api-reference" },
      { label: "价格页", url: "https://openai.com/api/pricing" },
    ],
    defaultModels: [
      {
        id: "gpt-5",
        name: "GPT-5",
        group: "GPT-5",
        provider: "openai",
        capabilities: {
          vision: true,
          toolUse: true,
          thinking: true,
          thinkingConfigType: "effort",
          reasoningEffortOptions: ["low", "medium", "high"],
        },
        description: "旗舰多模态模型，编码与代理任务王者（2025-10-03更新）",
      },
      {
        id: "gpt-5-pro",
        name: "GPT-5 Pro",
        group: "GPT-5",
        provider: "openai",
        capabilities: {
          vision: true,
          toolUse: true,
          thinking: true,
          thinkingConfigType: "effort",
          reasoningEffortOptions: ["low", "medium", "high"],
        },
        description: "开发者专属，API增强版",
      },
      {
        id: "gpt-5-nano",
        name: "GPT-5 Nano",
        group: "GPT-5",
        provider: "openai",
        description: "轻量高效，适合实时交互",
      },
      {
        id: "gpt-oss-120b",
        name: "GPT-OSS 120B",
        group: "GPT-OSS",
        provider: "openai",
        description: "开源变体，128K上下文",
      },
      {
        id: "gpt-image-2",
        name: "GPT Image 2",
        group: "GPT Image",
        provider: "openai",
        capabilities: { vision: true },
        description: "新一代图像生成，支持DALL-E 3集成",
      },
      {
        id: "gpt-image-1-mini",
        name: "GPT Image 1 Mini",
        group: "GPT Image",
        provider: "openai",
        capabilities: { vision: true },
        description: "轻量图像生成，快速输出（2025-04-15）",
      },
    ],
  },
  // OpenAI Responses API
  {
    type: "openai-responses",
    name: "OpenAI Responses",
    description: "OpenAI Responses API - 新一代有状态交互接口",
    defaultBaseUrl: "https://api.openai.com",
    logoUrl: "/model-icons/openai.svg",
    links: [
      { label: "控制台", url: "https://platform.openai.com" },
      { label: "API 文档", url: "https://platform.openai.com/docs/api-reference/responses" },
    ],
    defaultModels: [
      {
        id: "gpt-5.1",
        name: "GPT-5.1",
        group: "GPT-5",
        provider: "openai",
        capabilities: {
          vision: true,
          toolUse: true,
          webSearch: true,
          fileSearch: true,
          thinking: true,
          thinkingConfigType: "effort",
          reasoningEffortOptions: ["none", "minimal", "low", "medium", "high"],
        },
        description: "Responses旗舰，内置文件/网络搜索，多模态交互",
      },
      {
        id: "gpt-5.1-pro",
        name: "GPT-5.1 Pro",
        group: "GPT-5",
        provider: "openai",
        capabilities: {
          vision: true,
          toolUse: true,
          webSearch: true,
          fileSearch: true,
          thinking: true,
          thinkingConfigType: "effort",
          reasoningEffortOptions: ["none", "minimal", "low", "medium", "high"],
        },
        description: "开发者增强版，扩展工具集成",
      },
      {
        id: "gpt-5.1-compact",
        name: "GPT-5.1 Compact",
        group: "GPT-5",
        provider: "openai",
        capabilities: { toolUse: true, webSearch: true },
        description: "轻量版，快速响应，成本优化",
      },
      {
        id: "o3-pro",
        name: "o3-pro",
        group: "o3",
        provider: "openai",
        capabilities: {
          toolUse: true,
          thinking: true,
          thinkingConfigType: "budget",
        },
        description: "推理旗舰，可调节推理力度，复杂问题解决专家",
      },
      {
        id: "o3-mini",
        name: "o3-mini",
        group: "o3",
        provider: "openai",
        capabilities: {
          toolUse: true,
          thinking: true,
          thinkingConfigType: "budget",
        },
        description: "推理轻量版，高效逻辑推理",
      },
      {
        id: "gpt-4o-responses",
        name: "GPT-4o Responses",
        group: "GPT-4o",
        provider: "openai",
        capabilities: { vision: true, toolUse: true, webSearch: true },
        description: "4o系列Responses版，平衡性能与成本",
      },
    ],
  },
  // Moonshot (月之暗面 Kimi)
  {
    type: "openai",
    name: "Moonshot",
    description: "月之暗面 Kimi API",
    defaultBaseUrl: "https://api.moonshot.cn",
    logoUrl: "/model-icons/moonshot.svg",
    links: [
      { label: "官网", url: "https://www.moonshot.cn" },
      { label: "控制台", url: "https://platform.moonshot.cn/console" },
      { label: "API 文档", url: "https://platform.moonshot.cn/docs" },
      { label: "计费说明", url: "https://platform.moonshot.cn/pricing" },
    ],
    defaultModels: [
      {
        id: "kimi-k2-instruct",
        name: "Kimi K2 Instruct",
        group: "Kimi K2",
        provider: "moonshot",
        description: "1T参数MoE，256K上下文，编码/代理顶级",
      },
      {
        id: "kimi-k2-turbo-preview",
        name: "Kimi K2 Turbo Preview",
        group: "Kimi K2",
        provider: "moonshot",
        description: "Turbo优化，50%折扣期内高效版",
      },
      {
        id: "kimi-k2-0905",
        name: "Kimi K2 0905",
        group: "Kimi K2",
        provider: "moonshot",
        description: "开源权重，高级编码/工具集成（2025-09-05）",
      },
      {
        id: "moonshot-v1-128k",
        name: "Moonshot V1 128K",
        group: "Moonshot V1",
        provider: "moonshot",
      },
      {
        id: "moonshot-v1-32k",
        name: "Moonshot V1 32K",
        group: "Moonshot V1",
        provider: "moonshot",
      },
    ],
  },
  // 智谱 AI
  {
    type: "openai",
    name: "智谱 AI",
    description: "智谱 GLM API",
    defaultBaseUrl: "https://open.bigmodel.cn/api/paas/v4",
    logoUrl: "/model-icons/zhipu-color.svg",
    links: [
      { label: "官网", url: "https://open.bigmodel.cn/" },
      { label: "控制台", url: "https://open.bigmodel.cn/usercenter/apikeys" },
      { label: "API 文档", url: "https://open.bigmodel.cn/dev/api" },
      { label: "计费说明", url: "https://open.bigmodel.cn/pricing" },
    ],
    defaultModels: [
      {
        id: "glm-4.6",
        name: "GLM-4.6",
        group: "GLM-4.6",
        provider: "zhipu",
        description: "200K上下文，SAA升级，编码/代理对标Claude（2025-10-04）",
      },
      {
        id: "glm-4.6-air",
        name: "GLM-4.6 Air",
        group: "GLM-4.6",
        provider: "zhipu",
        description: "高速Agent/高并发优化",
      },
      {
        id: "glm-4.6v",
        name: "GLM-4.6V",
        group: "GLM-4.6",
        provider: "zhipu",
        capabilities: { vision: true },
        description: "多模态视觉语言模型",
      },
      {
        id: "glm-4.5",
        name: "GLM-4.5",
        group: "GLM-4.5",
        provider: "zhipu",
        capabilities: { toolUse: true },
        description: "开源代理专用，推理/编码增强（2025-07-28）",
      },
      { id: "glm-4-plus", name: "GLM-4 Plus", group: "GLM-4", provider: "zhipu" },
      { id: "glm-4-flash", name: "GLM-4 Flash", group: "GLM-4", provider: "zhipu" },
    ],
  },
  // Groq
  {
    type: "groq",
    name: "Groq",
    description: "Groq 高速推理 API",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    logoUrl: "/model-icons/groq.svg",
    links: [
      { label: "官网", url: "https://groq.com/" },
      { label: "控制台", url: "https://console.groq.com/" },
      { label: "API 文档", url: "https://console.groq.com/docs/" },
      { label: "计费说明", url: "https://wow.groq.com/pricing/" },
    ],
    defaultModels: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B Versatile",
        group: "Llama",
        provider: "groq",
        description: "多功能高速版",
      },
      {
        id: "llama-3.1-8b-instant",
        name: "Llama 3.1 8B Instant",
        group: "Llama",
        provider: "groq",
        description: "即时响应，轻量首选",
      },
      { id: "mixtral-8x7b-32768", name: "Mixtral 8x7B 32K", group: "Mixtral", provider: "groq" },
      {
        id: "gemma-2-9b",
        name: "Gemma 2 9B",
        group: "Gemma",
        provider: "groq",
        description: "高效开源，价格性能比高",
      },
      {
        id: "gpt-oss-120b",
        name: "GPT-OSS 120B",
        group: "GPT-OSS",
        provider: "groq",
        description: "开源变体，128K上下文",
      },
    ],
  },
  // Google Gemini
  {
    type: "gemini",
    name: "Google Gemini",
    description: "Google Gemini API",
    defaultBaseUrl: "https://generativelanguage.googleapis.com",
    logoUrl: "/model-icons/gemini-color.svg",
    links: [
      { label: "AI Studio", url: "https://aistudio.google.com" },
      { label: "API 文档", url: "https://ai.google.dev/gemini-api/docs" },
      { label: "价格页", url: "https://ai.google.dev/pricing" },
    ],
    defaultModels: [
      // 别名
      {
        id: "gemini-flash-lite-latest",
        name: "Gemini Flash Lite Latest",
        group: "Gemini",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          fileSearch: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "指向 Flash Lite 模型最新版本的别名",
      },
      {
        id: "gemini-flash-latest",
        name: "Gemini Flash Latest",
        group: "Gemini",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          fileSearch: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "指向 Flash 模型最新版本的别名",
      },
      {
        id: "gemini-pro-latest",
        name: "Gemini Pro Latest",
        group: "Gemini",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          fileSearch: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "指向 PRO 模型最新版本的别名",
      },
      // Gemini 3
      {
        id: "gemini-3-pro-preview",
        name: "Gemini 3 Pro",
        group: "Gemini 3",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          fileSearch: true,
          webSearch: true,
          codeExecution: true,
          thinking: true,
          thinkingConfigType: "effort",
          reasoningEffortOptions: ["low", "high"],
        },
        description: "旗舰多模态模型，支持文本、图像、视频、音频、PDF输入 (2025-11)",
      },
      {
        id: "gemini-3-pro-image-preview",
        name: "Gemini 3 Pro Image",
        group: "Gemini 3",
        provider: "gemini",
        capabilities: { vision: true, imageGeneration: true, preferChat: true },
        description: "图像生成和理解模型 (2025-11)",
      },
      // Gemini 2.5
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        group: "Gemini 2.5",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          fileSearch: true,
          webSearch: true,
          codeExecution: true,
          thinking: true,
          thinkingConfigType: "budget",
        },
        description: "先进思考模型，支持长上下文、代码、数学和STEM (2025-06)",
      },
      {
        id: "gemini-2.5-pro-preview-tts",
        name: "Gemini 2.5 Pro TTS",
        group: "Gemini 2.5",
        provider: "gemini",
        capabilities: { audio: true, fileSearch: true },
        description: "文本转语音模型 (2025-05)",
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        group: "Gemini 2.5",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          fileSearch: true,
          webSearch: true,
          codeExecution: true,
          thinking: true,
          thinkingConfigType: "budget",
        },
        description: "最佳性价比模型，适用于大规模、低延迟任务 (2025-06)",
      },
      {
        id: "gemini-2.5-flash-preview-09-2025",
        name: "Gemini 2.5 Flash Preview",
        group: "Gemini 2.5",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          fileSearch: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "Flash 的预览版本 (2025-09)",
      },
      {
        id: "gemini-2.5-flash-image",
        name: "Gemini 2.5 Flash Image",
        group: "Gemini 2.5",
        provider: "gemini",
        capabilities: { vision: true, imageGeneration: true, fileSearch: true, preferChat: true },
        description: "Flash 系列的图像生成模型 (2025-10)",
      },
      {
        id: "gemini-2.5-flash-native-audio-preview-09-2025",
        name: "Gemini 2.5 Flash Live",
        group: "Gemini 2.5",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          fileSearch: true,
          webSearch: true,
        },
        description: "实时音频和视频交互模型 (2025-09)",
      },
      {
        id: "gemini-2.5-flash-preview-tts",
        name: "Gemini 2.5 Flash TTS",
        group: "Gemini 2.5",
        provider: "gemini",
        capabilities: { audio: true, fileSearch: true },
        description: "Flash 系列的文本转语音模型 (2025-05)",
      },
      {
        id: "gemini-2.5-flash-lite",
        name: "Gemini 2.5 Flash-Lite",
        group: "Gemini 2.5",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "超快速模型，优化成本和吞吐量 (2025-07)",
      },
      {
        id: "gemini-2.5-flash-lite-preview-09-2025",
        name: "Gemini 2.5 Flash-Lite Preview",
        group: "Gemini 2.5",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "Flash-Lite 的预览版本 (2025-09)",
      },
      // Gemini 2.0
      {
        id: "gemini-2.0-flash",
        name: "Gemini 2.0 Flash",
        group: "Gemini 2.0",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "第二代主力模型，1M上下文 (2025-02)",
      },
      {
        id: "gemini-2.0-flash-preview-image-generation",
        name: "Gemini 2.0 Flash Image",
        group: "Gemini 2.0",
        provider: "gemini",
        capabilities: { vision: true, audio: true, imageGeneration: true, preferChat: true },
        description: "第二代图像生成模型 (2025-05)",
      },
      {
        id: "gemini-2.0-flash-live-001",
        name: "Gemini 2.0 Flash Live",
        group: "Gemini 2.0",
        provider: "gemini",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "第二代实时交互模型，将于2025-12-09弃用 (2025-04)",
      },
      {
        id: "gemini-2.0-flash-lite",
        name: "Gemini 2.0 Flash-Lite",
        group: "Gemini 2.0",
        provider: "gemini",
        capabilities: { vision: true, audio: true, toolUse: true },
        description: "第二代小型主力模型，1M上下文 (2025-02)",
      },
    ],
  },
  // Anthropic Claude
  {
    type: "claude",
    name: "Anthropic Claude",
    description: "Anthropic Claude API",
    defaultBaseUrl: "https://api.anthropic.com",
    logoUrl: "/model-icons/claude-color.svg",
    links: [
      { label: "控制台", url: "https://console.anthropic.com" },
      { label: "API 文档", url: "https://docs.anthropic.com/claude/reference/getting-started-with-the-api" },
      { label: "价格页", url: "https://www.anthropic.com/pricing" },
    ],
    defaultModels: [
      {
        id: "claude-haiku-4.5",
        name: "Claude Haiku 4.5",
        group: "Claude 4.5",
        provider: "anthropic",
        capabilities: { vision: true, toolUse: true, thinking: true, thinkingConfigType: "budget" },
        description: "小模型旗舰，成本敏感任务专家（2025-10-15）",
      },
      {
        id: "claude-sonnet-4.5-20250929",
        name: "Claude Sonnet 4.5",
        group: "Claude 4.5",
        provider: "anthropic",
        capabilities: { vision: true, toolUse: true, thinking: true, thinkingConfigType: "budget" },
        description: "编码/代理/计算机使用顶级，SWE-bench 77.2%（2025-09-29）",
      },
      {
        id: "claude-opus-4.1-20250805",
        name: "Claude Opus 4.1",
        group: "Claude 4",
        provider: "anthropic",
        capabilities: { vision: true, thinking: true, thinkingConfigType: "budget" },
        description: "旗舰推理模型",
      },
      {
        id: "claude-3.7-sonnet-20250219",
        name: "Claude 3.7 Sonnet",
        group: "Claude 3.7",
        provider: "anthropic",
        capabilities: { vision: true, thinking: true, thinkingConfigType: "budget" },
      },
    ],
  },
  // Cohere
  {
    type: "cohere",
    name: "Cohere",
    description: "Cohere API v2 - 企业级大语言模型服务",
    defaultBaseUrl: "https://api.cohere.com",
    logoUrl: "/model-icons/cohere-color.svg",
    links: [
      { label: "官网", url: "https://cohere.com/" },
      { label: "控制台", url: "https://dashboard.cohere.com/" },
      { label: "API 文档", url: "https://docs.cohere.com/" },
      { label: "计费说明", url: "https://cohere.com/pricing" },
    ],
    defaultModels: [
      {
        id: "command-a-reasoning",
        name: "Command A Reasoning",
        group: "Command A",
        provider: "cohere",
        capabilities: {
          toolUse: true,
          thinking: true,
          thinkingConfigType: "budget", // 支持预算配置
        },
        description: "企业推理旗舰，复杂 logic 分析，256K上下文（2025-08-22）",
      },
      {
        id: "command-a-vision",
        name: "Command A Vision",
        group: "Command A",
        provider: "cohere",
        capabilities: { vision: true, toolUse: true },
        description: "多模态视觉模型，图像理解与分析专家（2025-08-01）",
      },
      {
        id: "command-a-translate",
        name: "Command A Translate",
        group: "Command A",
        provider: "cohere",
        capabilities: { toolUse: true },
        description: "专业翻译模型，100+语言支持，企业级精准度（2025-08-28）",
      },
      {
        id: "command-a-code",
        name: "Command A Code",
        group: "Command A",
        provider: "cohere",
        capabilities: { toolUse: true },
        description: "代码生成专用模型，40+编程语言覆盖",
      },
      {
        id: "command-a-search",
        name: "Command A Search",
        group: "Command A",
        provider: "cohere",
        capabilities: { toolUse: true, webSearch: true },
        description: "搜索增强模型，实时信息检索与整合",
      },
      {
        id: "command-r-plus-08-2024",
        name: "Command R+ 08-2024",
        group: "Command R+",
        provider: "cohere",
        capabilities: { toolUse: true },
        description: "增强版R+，企业级稳定性和性能",
      },
      {
        id: "command-r-plus",
        name: "Command R+",
        group: "Command",
        provider: "cohere",
        capabilities: { toolUse: true },
        description: "企业级主力模型，平衡性能与成本",
      },
      {
        id: "command-light",
        name: "Command Light",
        group: "Command",
        provider: "cohere",
        description: "轻量级模型，快速响应场景",
      },
    ],
  },
  // Hugging Face (使用 OpenAI 兼容的 Chat Completion API)
  {
    type: "openai",
    name: "Hugging Face",
    description: "Hugging Face Chat Completion API (OpenAI 兼容)",
    defaultBaseUrl: "https://api-inference.huggingface.co",
    logoUrl: "/model-icons/huggingface-color.svg",
    links: [
      { label: "官网", url: "https://huggingface.co/" },
      { label: "API 文档", url: "https://huggingface.co/docs/inference-providers/index" },
      { label: "价格页", url: "https://huggingface.co/pricing" },
    ],
    defaultModels: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct",
        name: "Llama 3.3 70B Instruct",
        group: "Llama",
        provider: "huggingface",
      },
      {
        id: "meta-llama/Llama-3.1-8B-Instruct",
        name: "Llama 3.1 8B Instruct",
        group: "Llama",
        provider: "huggingface",
      },
      {
        id: "mistralai/Mixtral-8x7B-Instruct-v0.1",
        name: "Mixtral 8x7B Instruct",
        group: "Mixtral",
        provider: "huggingface",
      },
      {
        id: "microsoft/Phi-3-mini-4k-instruct",
        name: "Phi-3 Mini 4K",
        group: "Phi",
        provider: "huggingface",
      },
      {
        id: "Qwen/Qwen3-235B-A22B-Instruct",
        name: "Qwen3 235B Instruct",
        group: "Qwen3",
        provider: "huggingface",
        description: "MoE旗舰，开源热门",
      },
    ],
  },
  // Google Vertex AI
  {
    type: "vertexai",
    name: "Vertex AI",
    description: "Google Cloud Vertex AI - 企业级 Gemini 模型服务",
    defaultBaseUrl: "https://us-central1-aiplatform.googleapis.com",
    logoUrl: "/model-icons/vertexai-color.svg",
    links: [
      { label: "控制台", url: "https://console.cloud.google.com/vertex-ai" },
      { label: "API 文档", url: "https://cloud.google.com/vertex-ai/docs" },
      { label: "价格页", url: "https://cloud.google.com/vertex-ai/generative-ai/pricing" },
    ],
    defaultModels: [
      {
        id: "gemini-3-pro-preview",
        name: "Gemini 3 Pro",
        group: "Gemini 3",
        provider: "google",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          fileSearch: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "新一代企业级旗舰，高级推理、自主编码、复杂多模态",
      },
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        group: "Gemini 2.5",
        provider: "google",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          fileSearch: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "企业级旗舰，复杂任务王者，内置思考/编码工具",
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        group: "Gemini 2.5",
        provider: "google",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          fileSearch: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "高效企业版，成本优化，支持工具调用",
      },
      {
        id: "gemini-2.5-flash-lite",
        name: "Gemini 2.5 Flash-Lite",
        group: "Gemini 2.5",
        provider: "google",
        capabilities: {
          vision: true,
          audio: true,
          toolUse: true,
          webSearch: true,
          codeExecution: true,
        },
        description: "轻量企业版，端侧部署友好",
      },
      {
        id: "gemini-1.5-pro",
        name: "Gemini 1.5 Pro",
        group: "Gemini 1.5",
        provider: "google",
        capabilities: { vision: true, toolUse: true },
        description: "稳定企业版，1M上下文窗口",
      },
      {
        id: "gemini-1.5-flash",
        name: "Gemini 1.5 Flash",
        group: "Gemini 1.5",
        provider: "google",
        capabilities: { vision: true },
        description: "高速企业版，大吞吐量优化",
      },
      {
        id: "claude-haiku-4.5",
        name: "Claude Haiku 4.5",
        group: "Claude",
        provider: "google",
        capabilities: { vision: true, toolUse: true },
        description: "Anthropic模型集成（2025-10-15）",
      },
    ],
  },
  // 火山引擎（字节跳动）
  {
    type: "openai",
    name: "火山引擎",
    description: "字节跳动火山引擎 API",
    defaultBaseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    logoUrl: "/model-icons/volcengine-color.svg",
    links: [
      { label: "官网", url: "https://www.volcengine.com/product/ark" },
      { label: "控制台", url: "https://console.volcengine.com/ark" },
      { label: "API 文档", url: "https://www.volcengine.com/docs/82379/1099420" },
      { label: "计费说明", url: "https://www.volcengine.com/docs/82379/1099722" },
    ],
    defaultModels: [
      {
        id: "doubao-1.6",
        name: "Doubao 1.6",
        group: "Doubao",
        provider: "bytedance",
        capabilities: { toolUse: true },
        description: "全功能综合模型，256K上下文，自适应推理（2025-10）",
      },
      {
        id: "doubao-1.5-pro",
        name: "Doubao 1.5 Pro",
        group: "Doubao",
        provider: "bytedance",
        capabilities: { vision: true },
        description: "多模态升级，资源高效",
      },
      { id: "doubao-pro-256k", name: "豆包 Pro 256K", group: "豆包", provider: "bytedance" },
      { id: "doubao-pro-128k", name: "豆包 Pro 128K", group: "豆包", provider: "bytedance" },
      { id: "doubao-lite-128k", name: "豆包 Lite 128K", group: "豆包", provider: "bytedance" },
    ],
  },
  // xAI (Grok)
  {
    type: "xai",
    name: "xAI",
    description: "xAI Grok API",
    defaultBaseUrl: "https://api.x.ai/v1",
    logoUrl: "/model-icons/xai.svg",
    links: [
      { label: "官网", url: "https://x.ai" },
      { label: "控制台", url: "https://console.x.ai" },
      { label: "API 文档", url: "https://docs.x.ai" },
    ],
    defaultModels: [
      {
        id: "grok-4",
        name: "Grok 4",
        group: "Grok 4",
        provider: "xai",
        capabilities: { toolUse: true, webSearch: true },
        description: "旗舰，非正统风格，实时数据接入",
      },
      {
        id: "grok-4-heavy",
        name: "Grok 4 Heavy",
        group: "Grok 4",
        provider: "xai",
        description: "重型变体，基准超群",
      },
      {
        id: "grok-4-reasoning",
        name: "Grok 4 Reasoning",
        group: "Grok",
        provider: "xai",
        capabilities: {
          thinking: true,
          thinkingConfigType: "effort",
          reasoningEffortOptions: ["low", "high"],
        },
        description: "增强推理版，专攻复杂逻辑和编码",
      },
      {
        id: "imagine-v0.9",
        name: "Imagine v0.9",
        group: "Imagine",
        provider: "xai",
        capabilities: { vision: true },
        description: "图像生成，10月7日 rollout",
      },
      {
        id: "grok-4-fast",
        name: "Grok 4 Fast",
        group: "Grok 4",
        provider: "xai",
        description: "成本高效推理模型",
      },
    ],
  },
  // 阿里巴巴 Qwen
  {
    type: "openai",
    name: "阿里云百炼",
    description: "阿里云百炼，通义千问 Qwen API",
    defaultBaseUrl: "https://dashscope.aliyuncs.com/compatible-mode",
    logoUrl: "/model-icons/qwen-color.svg",
    links: [
      { label: "官网", url: "https://bailian.console.aliyun.com" },
      { label: "控制台", url: "https://bailian.console.aliyun.com/cn-beijing/?tab=model#/model-market" },
      { label: "API 文档", url: "https://bailian.console.aliyun.com/cn-beijing/doc?tab=doc#/doc" },
      {
        label: "计费说明",
        url: "https://bailian.console.aliyun.com/cn-beijing/doc?tab=doc#/doc/?type=model&url=2987148",
      },
    ],
    defaultModels: [
      {
        id: "qwen3-max-preview",
        name: "Qwen3 Max Preview",
        group: "Qwen3",
        provider: "qwen",
        description: "1T+参数，最强文本模型（2025-09-08）",
      },
      {
        id: "qwen3-next-80b-a3b",
        name: "Qwen3 Next 80B A3B",
        group: "Qwen3",
        provider: "qwen",
        description: "高效MoE，消费级硬件友好",
      },
      {
        id: "qwen3-235b-a22b",
        name: "Qwen3 235B-A22B",
        group: "Qwen3",
        provider: "qwen",
        description: "MoE架构极致性能旗舰（2025-10-14）",
      },
      {
        id: "qwen3-coder-480b",
        name: "Qwen3 Coder 480B",
        group: "Qwen3",
        provider: "qwen",
        description: "超大规模代码专用模型",
      },
      {
        id: "qwen3-vl-235b",
        name: "Qwen3 VL-235B",
        group: "Qwen3",
        provider: "qwen",
        capabilities: { vision: true },
        description: "视觉语言多模态模型（2025-10-14）",
      },
      {
        id: "qwen3-asr-flash",
        name: "Qwen3 ASR Flash",
        group: "Qwen3",
        provider: "qwen",
        description: "语音转录专用，超竞品（2025-09-08）",
      },
    ],
  },
  // Mistral AI
  {
    type: "openai",
    name: "Mistral AI",
    description: "Mistral AI 官方 API",
    defaultBaseUrl: "https://api.mistral.ai",
    logoUrl: "/model-icons/mistral-color.svg",
    links: [
      { label: "官网", url: "https://mistral.ai" },
      { label: "控制台", url: "https://console.mistral.ai" },
      { label: "API 文档", url: "https://docs.mistral.ai" },
      { label: "价格页", url: "https://mistral.ai/technology/#pricing" },
    ],
    defaultModels: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large Latest",
        group: "Mistral Large",
        provider: "mistral",
        capabilities: { toolUse: true },
        description: "旗舰模型，128K上下文",
      },
      {
        id: "mistral-small-latest",
        name: "Mistral Small Latest",
        group: "Mistral Small",
        provider: "mistral",
        description: "高效小模型，成本优化",
      },
      {
        id: "codestral-latest",
        name: "Codestral Latest",
        group: "Codestral",
        provider: "mistral",
        description: "代码专用模型，256K上下文",
      },
      {
        id: "magistral",
        name: "Magistral",
        group: "Magistral",
        provider: "mistral",
        capabilities: { thinking: true, thinkingConfigType: "switch" },
        description: "推理模型家族（2025-06-10）",
      },
    ],
  },
  // AI21 Labs
  {
    type: "openai",
    name: "AI21 Labs",
    description: "AI21 Labs Jamba API",
    defaultBaseUrl: "https://api.ai21.com/studio",
    logoUrl: "/model-icons/aionlabs-color.svg",
    links: [
      { label: "官网", url: "https://www.ai21.com" },
      { label: "控制台", url: "https://studio.ai21.com" },
      { label: "API 文档", url: "https://docs.ai21.com" },
      { label: "价格页", url: "https://www.ai21.com/pricing" },
    ],
    defaultModels: [
      {
        id: "jamba-reasoning-3b",
        name: "Jamba Reasoning 3B",
        group: "Jamba",
        provider: "ai21",
        capabilities: { toolUse: true },
        description: "小型推理模型，250K上下文，iPhone运行（2025-10-08）",
      },
      {
        id: "jamba-1.5-large",
        name: "Jamba 1.5 Large",
        group: "Jamba",
        provider: "ai21",
        capabilities: { toolUse: true },
        description: "SSM-Transformer混合架构，256K上下文",
      },
      {
        id: "jamba-1.5-mini",
        name: "Jamba 1.5 Mini",
        group: "Jamba",
        provider: "ai21",
        description: "轻量混合架构，256K上下文",
      },
    ],
  },
  // 百度文心
  {
    type: "openai",
    name: "百度文心",
    description: "百度文心一言 ERNIE API",
    defaultBaseUrl: "https://aip.baidubce.com",
    logoUrl: "/model-icons/wenxin-color.svg",
    links: [
      { label: "官网", url: "https://cloud.baidu.com/product/wenxinworkshop" },
      { label: "控制台", url: "https://console.bce.baidu.com/qianfan/ais/console/application/protocols" },
      { label: "API 文档", url: "https://cloud.baidu.com/doc/WENXINWORKSHOP/index.html" },
      { label: "计费说明", url: "https://cloud.baidu.com/doc/qianfan/s/wmh4sv6ya" },
    ],
    defaultModels: [
      {
        id: "ernie-4.5",
        name: "ERNIE 4.5",
        group: "ERNIE 4.5",
        provider: "baidu",
        capabilities: { toolUse: true },
        description: "开源企业级模型，Apache 2.0许可（2025-09-09）",
      },
      {
        id: "ernie-4.0-turbo-128k",
        name: "ERNIE 4.0 Turbo 128K",
        group: "ERNIE 4.0",
        provider: "baidu",
        capabilities: { toolUse: true },
        description: "旗舰模型，128K超长上下文",
      },
      {
        id: "ernie-x1.1",
        name: "ERNIE X1.1",
        group: "ERNIE X1",
        provider: "baidu",
        capabilities: { thinking: true, thinkingConfigType: "switch" },
        description: "推理模型升级，代理能力增强（2025-09-09）",
      },
      {
        id: "ernie-3.5-128k",
        name: "ERNIE 3.5 128K",
        group: "ERNIE 3.5",
        provider: "baidu",
        description: "性价比版本，128K上下文",
      },
    ],
  },
  // 腾讯混元
  {
    type: "openai",
    name: "腾讯混元",
    description: "腾讯混元大模型 API",
    defaultBaseUrl: "https://api.hunyuan.cloud.tencent.com",
    logoUrl: "/model-icons/hunyuan-color.svg",
    links: [
      { label: "官网", url: "https://hunyuan.tencent.com" },
      { label: "控制台", url: "https://console.cloud.tencent.com/hunyuan" },
      { label: "API 文档", url: "https://cloud.tencent.com/document/product/1729" },
      { label: "计费说明", url: "https://cloud.tencent.com/document/product/1729/97731" },
    ],
    defaultModels: [
      {
        id: "hunyuan-3.0",
        name: "Hunyuan 3.0",
        group: "Hunyuan",
        provider: "tencent",
        capabilities: { vision: true, toolUse: true },
        description: "图像生成模型，80B参数开源（2025-09-28）",
      },
      {
        id: "hunyuan-turbo",
        name: "混元 Turbo",
        group: "混元",
        provider: "tencent",
        capabilities: { toolUse: true },
        description: "高速推理，适合实时交互",
      },
      {
        id: "hunyuan-pro",
        name: "混元 Pro",
        group: "混元",
        provider: "tencent",
        capabilities: { vision: true, toolUse: true },
        description: "多模态旗舰，视觉理解增强",
      },
      {
        id: "hunyuan-lite",
        name: "混元 Lite",
        group: "混元",
        provider: "tencent",
        description: "轻量版，成本优化",
      },
      {
        id: "hunyuan-3d-3.0",
        name: "Hunyuan 3D 3.0",
        group: "Hunyuan",
        provider: "tencent",
        capabilities: { vision: true },
        description: "3D模型生成，1536³分辨率（2025-09-17）",
      },
    ],
  },
  // MiniMax
  {
    type: "openai",
    name: "MiniMax",
    description: "MiniMax ABAB API",
    defaultBaseUrl: "https://api.minimax.chat",
    logoUrl: "/model-icons/minimax-color.svg",
    links: [
      { label: "官网", url: "https://www.minimaxi.com" },
      { label: "控制台", url: "https://platform.minimaxi.com" },
      { label: "API 文档", url: "https://platform.minimaxi.com/docs/api-reference/api-overview" },
      { label: "计费说明", url: "https://platform.minimaxi.com/docs/guides/pricing-speech" },
    ],
    defaultModels: [
      {
        id: "abab6.5s-chat",
        name: "ABAB 6.5s Chat",
        group: "ABAB 6.5",
        provider: "minimax",
        capabilities: { toolUse: true },
        description: "旗舰对话模型，245K上下文",
      },
      {
        id: "abab6.5t-chat",
        name: "ABAB 6.5t Chat",
        group: "ABAB 6.5",
        provider: "minimax",
        description: "文本专用，高效处理",
      },
      {
        id: "abab6.5g-chat",
        name: "ABAB 6.5g Chat",
        group: "ABAB 6.5",
        provider: "minimax",
        capabilities: { vision: true },
        description: "多模态版本，支持图像理解",
      },
      {
        id: "minimax-01",
        name: "MiniMax-01",
        group: "MiniMax",
        provider: "minimax",
        description: "456B参数模型，MMLU 88.5%（2025-01）",
      },
      {
        id: "minimax-m1",
        name: "MiniMax-M1",
        group: "MiniMax",
        provider: "minimax",
        description: "开源1M令牌上下文模型（2025-06-16）",
      },
    ],
  },
  // 零一万物
  {
    type: "openai",
    name: "零一万物",
    description: "零一万物 Yi API",
    defaultBaseUrl: "https://api.01.ai",
    logoUrl: "/model-icons/yi-color.svg",
    defaultModels: [
      {
        id: "yi-lightning",
        name: "Yi Lightning",
        group: "Yi",
        provider: "01ai",
        capabilities: { toolUse: true },
        description: "超高速推理，4M上下文（2024-10-16）",
      },
      {
        id: "yi-lightning-lite",
        name: "Yi Lightning Lite",
        group: "Yi",
        provider: "01ai",
        capabilities: { toolUse: true },
        description: "轻量版高速推理",
      },
      {
        id: "yi-large",
        name: "Yi Large",
        group: "Yi",
        provider: "01ai",
        capabilities: { toolUse: true },
        description: "旗舰模型，200K上下文",
      },
      {
        id: "yi-medium",
        name: "Yi Medium",
        group: "Yi",
        provider: "01ai",
        description: "平衡性能，16K上下文",
      },
    ],
  },
  // 百川智能
  {
    type: "openai",
    name: "百川智能",
    description: "百川智能 API",
    defaultBaseUrl: "https://api.baichuan-ai.com",
    logoUrl: "/model-icons/baichuan-color.svg",
    defaultModels: [
      {
        id: "baichuan4",
        name: "Baichuan 4",
        group: "Baichuan",
        provider: "baichuan",
        capabilities: { toolUse: true },
        description: "旗舰模型，128K上下文",
      },
      {
        id: "baichuan-omni",
        name: "Baichuan-Omni",
        group: "Baichuan",
        provider: "baichuan",
        capabilities: { vision: true },
        description: "7B多模态模型，支持图像/视频/音频/文本（2024-10-18）",
      },
      {
        id: "baichuan3-turbo",
        name: "Baichuan 3 Turbo",
        group: "Baichuan",
        provider: "baichuan",
        description: "高速版本，32K上下文",
      },
    ],
  },
  // 商汤日日新
  {
    type: "openai",
    name: "商汤日日新",
    description: "商汤 SenseNova API",
    defaultBaseUrl: "https://api.sensenova.cn",
    logoUrl: "/model-icons/sensenova-color.svg",
    links: [
      { label: "官网", url: "https://www.sensetime.com" },
      { label: "控制台", url: "https://platform.sensenova.cn" },
      { label: "API 文档", url: "https://platform.sensenova.cn/product/APIService/document/" },
    ],
    defaultModels: [
      {
        id: "sensenova-v6.5",
        name: "SenseNova V6.5",
        group: "SenseNova",
        provider: "sensenova",
        capabilities: { toolUse: true },
        description: "升级系列，多模态增强（2025-07-30）",
      },
      {
        id: "sensenova-5.5",
        name: "日日新 5.5",
        group: "日日新",
        provider: "sensenova",
        capabilities: { toolUse: true },
        description: "旗舰对话模型，知识增强",
      },
      {
        id: "sensenova-5.0-turbo",
        name: "日日新 5.0 Turbo",
        group: "日日新",
        provider: "sensenova",
        description: "高速版本，实时响应",
      },
    ],
  },
  // OpenRouter
  {
    type: "openrouter",
    name: "OpenRouter",
    description: "OpenRouter - 统一多个 AI 模型的聚合 API",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    logoUrl: "/model-icons/openrouter.svg",
    links: [
      { label: "官网", url: "https://openrouter.ai" },
      { label: "API 文档", url: "https://openrouter.ai/docs" },
      { label: "模型列表", url: "https://openrouter.ai/models" },
    ],
    defaultModels: [
      {
        id: "anthropic/claude-haiku-4.5",
        name: "Claude Haiku 4.5",
        group: "Claude",
        provider: "openrouter",
        capabilities: { vision: true, toolUse: true },
        description: "通过 OpenRouter 访问 Claude（2025-10-15）",
      },
      {
        id: "google/gemini-2.5-flash-preview-09-2025",
        name: "Gemini 2.5 Flash (Free)",
        group: "Gemini",
        provider: "openrouter",
        capabilities: { vision: true },
        description: "免费访问 Gemini Flash",
      },
      {
        id: "deepseek/deepseek-chat",
        name: "DeepSeek Chat",
        group: "DeepSeek",
        provider: "openrouter",
        description: "通过 OpenRouter 访问 DeepSeek",
      },
    ],
  },
  // SiliconFlow
  {
    type: "siliconflow",
    name: "SiliconFlow",
    description: "硅基流动 - 高性价比 AI 推理服务",
    defaultBaseUrl: "https://api.siliconflow.cn/v1",
    logoUrl: "/model-icons/siliconcloud-color.svg",
    links: [
      { label: "控制台", url: "https://cloud.siliconflow.cn" },
      { label: "API 文档", url: "https://docs.siliconflow.cn" },
      { label: "价格页", url: "https://siliconflow.cn/zh-cn/pricing" },
    ],
    defaultModels: [
      {
        id: "deepseek-ai/DeepSeek-V3.2-Exp",
        name: "DeepSeek V3.2-Exp",
        group: "DeepSeek",
        provider: "siliconflow",
        description: "极致性价比，685B MoE（2025-09-29）",
      },
      {
        id: "Qwen/Qwen2.5-72B-Instruct",
        name: "Qwen 2.5 72B Instruct",
        group: "Qwen",
        provider: "siliconflow",
        description: "阿里千问开源旗舰",
      },
      {
        id: "meta-llama/Llama-3.3-70B-Instruct",
        name: "Llama 3.3 70B Instruct",
        group: "Llama",
        provider: "siliconflow",
        description: "Meta 开源大模型",
      },
      {
        id: "qwen/qwen3-vl-235b-instruct",
        name: "Qwen3-VL-235B-Instruct",
        group: "Qwen3",
        provider: "siliconflow",
        capabilities: { vision: true },
        description: "235B参数视觉模型（2025-10-14）",
      },
    ],
  },
  // Together AI
  {
    type: "openai",
    name: "Together AI",
    description: "Together AI - 开源模型推理平台",
    defaultBaseUrl: "https://api.together.xyz",
    logoUrl: "/model-icons/together-color.svg",
    links: [
      { label: "官网", url: "https://www.together.ai" },
      { label: "控制台", url: "https://api.together.xyz" },
      { label: "API 文档", url: "https://docs.together.ai" },
      { label: "价格页", url: "https://www.together.ai/pricing" },
    ],
    defaultModels: [
      {
        id: "meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo",
        name: "Llama 3.1 405B Turbo",
        group: "Llama",
        provider: "together",
        capabilities: { toolUse: true },
        description: "超大规模开源模型",
      },
      {
        id: "Qwen/Qwen2.5-72B-Instruct-Turbo",
        name: "Qwen 2.5 72B Turbo",
        group: "Qwen",
        provider: "together",
        description: "千问高速版",
      },
    ],
  },
  // Fireworks AI
  {
    type: "openai",
    name: "Fireworks AI",
    description: "Fireworks AI - 超快速推理平台",
    defaultBaseUrl: "https://api.fireworks.ai",
    logoUrl: "/model-icons/fireworks-color.svg",
    links: [
      { label: "官网", url: "https://fireworks.ai" },
      { label: "控制台", url: "https://console.fireworks.ai" },
      { label: "API 文档", url: "https://docs.fireworks.ai" },
      { label: "价格页", url: "https://fireworks.ai/pricing" },
    ],
    defaultModels: [
      {
        id: "accounts/fireworks/models/llama-v3p3-70b-instruct",
        name: "Llama 3.3 70B Instruct",
        group: "Llama",
        provider: "fireworks",
        description: "高速 Llama 推理",
      },
      {
        id: "accounts/fireworks/models/qwen2p5-72b-instruct",
        name: "Qwen 2.5 72B Instruct",
        group: "Qwen",
        provider: "fireworks",
        description: "高速千问推理",
      },
    ],
  },
  // DeepInfra
  {
    type: "openai",
    name: "DeepInfra",
    description: "DeepInfra - 开源模型托管服务",
    defaultBaseUrl: "https://api.deepinfra.com",
    logoUrl: "/model-icons/deepinfra-color.svg",
    links: [
      { label: "官网", url: "https://deepinfra.com" },
      { label: "控制台", url: "https://deepinfra.com/dash" },
      { label: "API 文档", url: "https://deepinfra.com/docs" },
      { label: "价格页", url: "https://deepinfra.com/pricing" },
    ],
    defaultModels: [
      {
        id: "meta-llama/Meta-Llama-3.1-70B-Instruct",
        name: "Llama 3.1 70B Instruct",
        group: "Llama",
        provider: "deepinfra",
        description: "Meta 开源模型",
      },
      {
        id: "Qwen/Qwen2.5-72B-Instruct",
        name: "Qwen 2.5 72B Instruct",
        group: "Qwen",
        provider: "deepinfra",
        description: "阿里千问",
      },
    ],
  },
  // Perplexity
  {
    type: "openai",
    name: "Perplexity",
    description: "Perplexity AI - 搜索增强模型",
    defaultBaseUrl: "https://api.perplexity.ai",
    logoUrl: "/model-icons/perplexity-color.svg",
    links: [
      { label: "官网", url: "https://www.perplexity.ai" },
      { label: "API 文档", url: "https://docs.perplexity.ai" },
    ],
    defaultModels: [
      {
        id: "sonar-pro",
        name: "Sonar Pro",
        group: "Sonar",
        provider: "perplexity",
        capabilities: { webSearch: true },
        description: "联网搜索增强，实时信息",
      },
      {
        id: "sonar",
        name: "Sonar",
        group: "Sonar",
        provider: "perplexity",
        capabilities: { webSearch: true },
        description: "标准联网版本",
      },
    ],
  },
  // Azure OpenAI
  {
    type: "azure",
    name: "Azure OpenAI",
    description: "微软 Azure OpenAI 服务",
    defaultBaseUrl: "https://{resource}.openai.azure.com/openai/deployments/{deployment}",
    logoUrl: "/model-icons/azure-color.svg",
    links: [
      { label: "官网", url: "https://azure.microsoft.com/products/ai-services/openai-service" },
      { label: "控制台", url: "https://portal.azure.com" },
      { label: "API 文档", url: "https://learn.microsoft.com/azure/ai-services/openai/" },
    ],
    defaultModels: [
      {
        id: "gpt-5",
        name: "GPT-5",
        group: "GPT-5",
        provider: "microsoft",
        capabilities: { vision: true, toolUse: true },
        description: "Azure 托管的 GPT-5（2025-10-03）",
      },
      {
        id: "gpt-4o",
        name: "GPT-4o",
        group: "GPT-4o",
        provider: "microsoft",
        capabilities: { vision: true, toolUse: true },
        description: "Azure 托管的 GPT-4o",
      },
      {
        id: "gpt-4-turbo",
        name: "GPT-4 Turbo",
        group: "GPT-4",
        provider: "microsoft",
        capabilities: { vision: true },
        description: "Azure 托管的 GPT-4 Turbo",
      },
      {
        id: "gpt-image-1-mini",
        name: "GPT Image 1 Mini",
        group: "GPT Image",
        provider: "microsoft",
        capabilities: { vision: true },
        description: "图像生成模型（2025-10-06）",
      },
      {
        id: "gpt-35-turbo",
        name: "GPT-3.5 Turbo",
        group: "GPT-3.5",
        provider: "microsoft",
        description: "Azure 托管的 GPT-3.5",
      },
    ],
  },
  // 魔搭 ModelScope
  {
    type: "openai",
    name: "魔搭 ModelScope",
    description: "魔搭社区 API-Inference 服务（OpenAI兼容）",
    defaultBaseUrl: "https://api-inference.modelscope.cn/v1",
    logoUrl: "/model-icons/modelscope-color.svg",
    links: [
      { label: "官网", url: "https://modelscope.cn" },
      { label: "模型推理", url: "https://modelscope.cn/models" },
      { label: "API 文档", url: "https://modelscope.cn/docs/model-service/API-Inference/intro" },
    ],
    defaultModels: [
      {
        id: "Qwen/Qwen3-235B-A22B-Instruct-2507",
        name: "Qwen3 235B-A22B Instruct",
        group: "Qwen3",
        provider: "modelscope",
        capabilities: { toolUse: true },
        description: "Qwen3旗舰，MoE架构，235B参数（2025-10-14）",
      },
      {
        id: "Qwen/Qwen3-235B-A22B-Thinking-2507",
        name: "Qwen3 235B-A22B Thinking",
        group: "Qwen3",
        provider: "modelscope",
        capabilities: { toolUse: true },
        description: "Qwen3推理版本，深度思考能力",
      },
      {
        id: "Qwen/Qwen3-VL-235B-A22B-Instruct",
        name: "Qwen3-VL-235B-A22B",
        group: "Qwen3",
        provider: "modelscope",
        capabilities: { vision: true, toolUse: true },
        description: "Qwen3视觉语言模型，235B参数多模态旗舰",
      },
      {
        id: "Qwen/Qwen3-Next-80B-A3B-Instruct",
        name: "Qwen3-Next-80B-A3B",
        group: "Qwen3",
        provider: "modelscope",
        capabilities: { toolUse: true },
        description: "Qwen3高效版本，MoE架构",
      },
      {
        id: "Qwen/Qwen3-30B-A3B-Thinking-2507",
        name: "Qwen3 30B-A3B Thinking",
        group: "Qwen3",
        provider: "modelscope",
        capabilities: { toolUse: true },
        description: "Qwen3推理模型，30B参数高效版",
      },
      {
        id: "Qwen/Qwen3-Coder-30B-A3B-Instruct",
        name: "Qwen3-Coder-30B-A3B",
        group: "Qwen3",
        provider: "modelscope",
        description: "Qwen3代码专用模型，30B参数",
      },
      {
        id: "Qwen/QwQ-32B-Preview",
        name: "QwQ-32B-Preview",
        group: "Qwen",
        provider: "modelscope",
        capabilities: { toolUse: true },
        description: "推理专用模型，32B参数",
      },
      {
        id: "Qwen/QVQ-72B-Preview",
        name: "QVQ-72B-Preview",
        group: "Qwen",
        provider: "modelscope",
        capabilities: { vision: true },
        description: "视觉推理模型，72B参数",
      },
      {
        id: "deepseek-ai/DeepSeek-V3.2-Exp",
        name: "DeepSeek-V3.2-Exp",
        group: "DeepSeek",
        provider: "modelscope",
        description: "实验版MoE模型，DSA稀疏注意力（2025-09-29）",
      },
      {
        id: "deepseek-ai/DeepSeek-R1-0528",
        name: "DeepSeek-R1-0528",
        group: "DeepSeek",
        provider: "modelscope",
        capabilities: { toolUse: true },
        description: "Dense推理旗舰，混合V3.1架构（限额200次/天）",
      },
      {
        id: "ZhipuAI/GLM-4.6",
        name: "GLM-4.6",
        group: "GLM",
        provider: "modelscope",
        capabilities: { toolUse: true },
        description: "智谱最新旗舰，200K上下文（2025-10-04）",
      },
      {
        id: "ZhipuAI/GLM-4.5",
        name: "GLM-4.5",
        group: "GLM",
        provider: "modelscope",
        capabilities: { toolUse: true },
        description: "智谱开源代理专用（2025-07-28）",
      },
      {
        id: "MiniMax/MiniMax-M1-80k",
        name: "MiniMax-M1-80k",
        group: "MiniMax",
        provider: "modelscope",
        description: "1M令牌上下文模型（2025-06-16）",
      },
      {
        id: "Shanghai_AI_Laboratory/Intern-S1",
        name: "Intern-S1",
        group: "Intern",
        provider: "modelscope",
        description: "上海AI实验室推理模型",
      },
      {
        id: "OpenGVLab/InternVL3_5-241B-A28B",
        name: "InternVL3.5-241B",
        group: "Intern",
        provider: "modelscope",
        capabilities: { vision: true },
        description: "开源视觉语言模型，241B参数",
      },
      {
        id: "stepfun-ai/step3",
        name: "Step-3",
        group: "Step",
        provider: "modelscope",
        description: "阶跃星辰最新模型",
      },
      {
        id: "iic/Tongyi-DeepResearch-30B-A3B",
        name: "通义DeepResearch-30B",
        group: "通义",
        provider: "modelscope",
        description: "深度研究专用模型，30B参数",
      },
    ],
  },
  // Ollama (本地)
  {
    type: "ollama",
    name: "Ollama",
    description: "本地 Ollama 服务",
    defaultBaseUrl: "http://localhost:11434",
    logoUrl: "/model-icons/ollama.svg",
    links: [
      { label: "官网", url: "https://ollama.com" },
      { label: "GitHub", url: "https://github.com/ollama/ollama" },
      { label: "模型库", url: "https://ollama.com/library" },
    ],
  },
  // NewAPI / One API 聚合
  {
    type: "openai",
    name: "NewAPI",
    description: "NewAPI / One API 兼容的聚合服务",
    defaultBaseUrl: "https://api.example.com",
    logoUrl: "/model-icons/newapi-color.svg",
    links: [
      { label: "GitHub (NewAPI)", url: "https://github.com/Calcium-Ion/new-api" },
      { label: "API 文档 (NewAPI)", url: "https://docs.newapi.pro/zh/docs" },
      { label: "GitHub (One API)", url: "https://github.com/songquanpeng/one-api" },
    ],
  },
  // Suno (NewAPI)
  {
    type: "openai",
    name: "Suno (NewAPI)",
    description: "通过 NewAPI 访问的 Suno 音乐生成服务",
    defaultBaseUrl: "https://api.example.com",
    logoUrl: "/model-icons/suno.svg",
    links: [
      { label: "Suno 官网", url: "https://suno.com" },
      { label: "API 项目", url: "https://github.com/Suno-API/Suno-API" },
      { label: "Suno API文档", url: "https://github.com/Suno-API/Suno-API/blob/main/README_ZH.md" },
      { label: "API 文档 (NewAPI)", url: "https://github.com/Suno-API/Suno-API/blob/main/Suno.md" },
    ],
    defaultModels: [
      {
        id: "suno_music",
        name: "Suno Music",
        group: "Suno",
        provider: "suno",
        description: "音乐生成 (支持自定义/灵感模式)",
      },
      {
        id: "suno_lyrics",
        name: "Suno Lyrics",
        group: "Suno",
        provider: "suno",
        description: "歌词生成",
      },
      {
        id: "suno_uploads",
        name: "Suno Uploads",
        group: "Suno",
        provider: "suno",
        description: "音频上传",
      },
      {
        id: "suno_concat",
        name: "Suno Concat",
        group: "Suno",
        provider: "suno",
        description: "歌曲合并",
      },
      {
        id: "suno_act_mp4",
        name: "Suno MP4",
        group: "Suno Action",
        provider: "suno",
        description: "生成视频",
      },
      {
        id: "suno_act_stems",
        name: "Suno Stems",
        group: "Suno Action",
        provider: "suno",
        description: "分离音轨",
      },
      {
        id: "suno_act_timing",
        name: "Suno Timing",
        group: "Suno Action",
        provider: "suno",
        description: "歌词时间戳",
      },
      {
        id: "suno_act_wav",
        name: "Suno WAV",
        group: "Suno Action",
        provider: "suno",
        description: "无损音频",
      },
      {
        id: "suno_persona_create",
        name: "Suno Persona",
        group: "Suno Persona",
        provider: "suno",
        description: "创建角色",
      },
    ],
  },
];

/**
 * 根据名称获取预设模板
 */
export function getPresetByName(name: string): LlmPreset | undefined {
  return llmPresets.find((p) => p.name === name);
}
