// Copyright 2025-2026 miaotouy(Github@miaotouy)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * LLM 服务提供商类型配置
 */

import type { ProviderType, ProviderTypeInfo } from "../types/llm-profiles";

/**
 * 支持的 LLM 服务提供商类型列表
 */
export const providerTypes: ProviderTypeInfo[] = [
  {
    type: "openai",
    name: "OpenAI",
    description: "OpenAI 官方服务，支持聊天、绘图、语音和视频生成",
    defaultBaseUrl: "https://api.openai.com",
    supportsModelList: true,
    modelListEndpoint: "models",
    supportedParameters: {
      temperature: true,
      maxTokens: true,
      topP: true,
      frequencyPenalty: true,
      presencePenalty: true,
      seed: true,
      stop: true,
      maxCompletionTokens: true,
      reasoningEffort: true,
      logprobs: true,
      topLogprobs: true,
      responseFormat: true,
      tools: true,
      toolChoice: true,
      parallelToolCalls: true,
      thinking: true,
      webSearch: true,
      modalities: true,
      audio: true,
      prediction: true,
    },
  },
  {
    type: "openai-compatible",
    name: "OpenAI-Compatible",
    description: "通用 OpenAI 兼容格式，适用于大多数第三方中转或自建服务",
    defaultBaseUrl: "",
    supportsModelList: true,
    modelListEndpoint: "models",
    supportedParameters: {
      temperature: true,
      maxTokens: true,
      topP: true,
      frequencyPenalty: true,
      presencePenalty: true,
      seed: true,
      stop: true,
      responseFormat: true,
      tools: true,
      toolChoice: true,
      parallelToolCalls: true,
      reasoningEffort: true,
      thinking: true,
    },
  },
  {
    type: "deepseek",
    name: "DeepSeek",
    description: "DeepSeek 官方 API，支持深度思考和联网搜索",
    defaultBaseUrl: "https://api.deepseek.com",
    supportsModelList: true,
    modelListEndpoint: "models",
    supportedParameters: {
      temperature: true,
      maxTokens: true,
      topP: true,
      frequencyPenalty: true,
      presencePenalty: true,
      stop: true,
      responseFormat: true,
      tools: true,
      thinking: true,
    },
  },
  {
    type: "claude",
    name: "Anthropic Claude",
    description: "Anthropic Claude API",
    defaultBaseUrl: "https://api.anthropic.com",
    supportsModelList: true,
    modelListEndpoint: "models",
    supportedParameters: {
      // 基础参数
      temperature: true,
      maxTokens: true,
      topP: true,
      topK: true,
      stop: true,
      // 高级参数
      tools: true,
      toolChoice: true,
      parallelToolCalls: true,
      // 特殊功能
      thinking: true,
      webSearch: true,
    },
    endpointPlaceholders: {
      chatCompletions: "/v1/messages",
      anthropicMessages: "/v1/messages",
      completions: "暂不支持",
      embeddings: "暂不支持",
      imagesGenerations: "暂不支持",
      imagesEdits: "暂不支持",
      imagesVariations: "暂不支持",
      audioSpeech: "暂不支持",
      audioTranscriptions: "暂不支持",
      audioTranslations: "暂不支持",
      videos: "暂不支持",
      videoStatus: "暂不支持",
      rerank: "暂不支持",
      moderations: "暂不支持",
    },
  },
  {
    type: "gemini",
    name: "Google Gemini",
    description: "Google Gemini API",
    defaultBaseUrl: "https://generativelanguage.googleapis.com",
    supportsModelList: true,
    modelListEndpoint: "models",
    supportedParameters: {
      // 基础参数
      temperature: true,
      maxTokens: true,
      topP: true,
      topK: true,
      frequencyPenalty: true,
      presencePenalty: true,
      seed: true,
      stop: true,
      // 高级参数
      logprobs: true,
      topLogprobs: true,
      responseFormat: true,
      tools: true,
      toolChoice: true,
      // 特殊功能
      thinking: true, // 思考能力（具体显示哪种控件由 Model 的 thinkingConfigType 决定）
      thinkingConfig: true,
      thinkingLevel: true,
      mediaResolution: true,
      codeExecution: true,
      modalities: true,
      safetySettings: true,
      webSearch: true,
    },
    endpointPlaceholders: {
      chatCompletions: "models/{model}:generateContent",
      geminiGenerateContent: "/v1beta/models/{model}:generateContent",
      completions: "暂不支持",
      models: "models",
      embeddings: "models/{model}:embedContent",
      imagesGenerations: "models/{model}:generateContent",
      imagesEdits: "暂不支持",
      imagesVariations: "暂不支持",
      audioSpeech: "models/{model}:generateContent",
      audioTranscriptions: "models/{model}:generateContent",
      audioTranslations: "models/{model}:generateContent",
      videos: "models/{model}:predictLongRunning",
      videoStatus: "暂不支持",
      rerank: "暂不支持",
      moderations: "暂不支持",
    },
  },
  {
    type: "siliconflow",
    name: "SiliconFlow",
    description: "硅基流动 - 极速推理平台，支持聊天、绘图、视频生成",
    defaultBaseUrl: "https://api.siliconflow.cn/v1",
    supportsModelList: true,
    modelListEndpoint: "https://aiping.cn/api/v1/models",
    supportedParameters: {
      temperature: true,
      maxTokens: true,
      topP: true,
      topK: true,
      frequencyPenalty: true,
      presencePenalty: true,
      seed: true,
      stop: true,
      responseFormat: true,
      tools: true,
    },
  },
  {
    type: "groq",
    name: "Groq",
    description: "Groq LPU 极速推理服务",
    defaultBaseUrl: "https://api.groq.com/openai/v1",
    supportsModelList: true,
    modelListEndpoint: "models",
    supportedParameters: {
      temperature: true,
      maxTokens: true,
      topP: true,
      seed: true,
      stop: true,
      tools: true,
    },
  },
  {
    type: "ollama",
    name: "Ollama",
    description: "本地 Llama 运行环境，支持多种开源模型",
    defaultBaseUrl: "http://localhost:11434",
    supportsModelList: true,
    modelListEndpoint: "api/tags",
    supportedParameters: {
      temperature: true,
      maxTokens: true,
      topP: true,
      topK: true,
      seed: true,
      stop: true,
    },
    endpointPlaceholders: {
      chatCompletions: "/api/chat",
      completions: "/api/generate",
      models: "/api/tags",
      embeddings: "/api/embed",
      imagesEdits: "暂不支持",
      imagesVariations: "暂不支持",
      audioSpeech: "暂不支持",
      audioTranscriptions: "暂不支持",
      audioTranslations: "暂不支持",
      videos: "暂不支持",
      videoStatus: "暂不支持",
      rerank: "暂不支持",
      moderations: "暂不支持",
    },
  },
  {
    type: "openrouter",
    name: "OpenRouter",
    description: "OpenRouter 统一模型网关",
    defaultBaseUrl: "https://openrouter.ai/api/v1",
    supportsModelList: true,
    modelListEndpoint: "models",
    supportedParameters: {
      temperature: true,
      maxTokens: true,
      topP: true,
      seed: true,
      stop: true,
      tools: true,
    },
  },
  {
    type: "openai-responses",
    name: "OpenAI Responses",
    description:
      "OpenAI Responses API - 新一代有状态交互接口，支持工具调用、推理、网络搜索、文件搜索等高级功能",
    defaultBaseUrl: "https://api.openai.com",
    supportsModelList: true,
    modelListEndpoint: "models",
    supportedParameters: {
      // 基础参数
      temperature: true,
      maxTokens: true,
      topP: true,
      stop: true,
      // 高级参数
      responseFormat: true,
      tools: true,
      toolChoice: true,
      parallelToolCalls: true,
      maxCompletionTokens: true,
      reasoningEffort: true,
      // 特殊功能
      webSearch: true,
      fileSearch: true,
      thinking: true,
      modalities: true,
    },
    endpointPlaceholders: {
      chatCompletions: "/v1/responses",
      responses: "/v1/responses",
      completions: "暂不支持",
      imagesGenerations: "/v1/responses",
      imagesEdits: "/v1/responses",
      imagesVariations: "暂不支持",
    },
  },
  {
    type: "cohere",
    name: "Cohere",
    description: "Cohere API (v2 格式)",
    defaultBaseUrl: "https://api.cohere.com",
    supportsModelList: true,
    modelListEndpoint: "models",
    supportedParameters: {
      // 基础参数
      temperature: true,
      maxTokens: true,
      topP: true,
      topK: true,
      frequencyPenalty: true,
      presencePenalty: true,
      seed: true,
      stop: true,
      // 高级参数
      tools: true,
      toolChoice: true,
      // 特殊功能
      thinking: true,
      thinkingConfig: true, // 允许配置思考参数
    },
    endpointPlaceholders: {
      chatCompletions: "/v2/chat",
      completions: "暂不支持",
      embeddings: "/v2/embed",
      rerank: "/v2/rerank",
      imagesGenerations: "暂不支持",
      imagesEdits: "暂不支持",
      imagesVariations: "暂不支持",
      audioSpeech: "暂不支持",
      audioTranscriptions: "/v2/audio/transcriptions",
      audioTranslations: "暂不支持",
      videos: "暂不支持",
      videoStatus: "暂不支持",
      moderations: "暂不支持",
    },
  },
  {
    type: "azure",
    name: "Azure OpenAI",
    description: "微软 Azure OpenAI 服务",
    defaultBaseUrl:
      "https://{resource}.openai.azure.com/openai/deployments/{deployment}",
    supportsModelList: false,
    supportedParameters: {
      temperature: true,
      maxTokens: true,
      topP: true,
      frequencyPenalty: true,
      presencePenalty: true,
      seed: true,
      stop: true,
      responseFormat: true,
      tools: true,
      toolChoice: true,
    },
    configFields: [
      {
        id: "azure-resource",
        label: "资源名称",
        component: "ElInput",
        modelPath: "resource",
        props: {
          placeholder: "your-resource-name",
        },
        hint: "Azure OpenAI 资源名称",
        keywords: "resource",
      },
      {
        id: "azure-deployment",
        label: "部署名称",
        component: "ElInput",
        modelPath: "deployment",
        props: {
          placeholder: "gpt-4o",
        },
        hint: "部署的 Deployment ID",
        keywords: "deployment",
      },
      {
        id: "azure-api-version",
        label: "API 版本",
        component: "ElInput",
        modelPath: "apiVersion",
        defaultValue: "2024-12-01-preview",
        hint: "Azure OpenAI 的 API 版本 (api-version 参数)，例如 2024-12-01-preview",
        keywords: "azure api version",
      },
    ],
  },
  {
    type: "vertexai",
    name: "Vertex AI",
    description: "Google Cloud Vertex AI API（基于 Gemini）",
    defaultBaseUrl: "https://us-central1-aiplatform.googleapis.com",
    supportsModelList: true,
    modelListEndpoint: "models",
    supportedParameters: {
      temperature: true,
      maxTokens: true,
      topP: true,
      topK: true,
      frequencyPenalty: true,
      presencePenalty: true,
      seed: true,
      stop: true,
      logprobs: true,
      topLogprobs: true,
      responseFormat: true,
      tools: true,
      toolChoice: true,
      thinking: true,
      thinkingConfig: true,
      thinkingLevel: true,
      mediaResolution: true,
      codeExecution: true,
      modalities: true,
      safetySettings: true,
      webSearch: true,
    },
    configFields: [
      {
        id: "vertex-project-id",
        label: "Project ID",
        component: "ElInput",
        modelPath: "projectId",
        hint: "Google Cloud 项目 ID",
        keywords: "project id",
      },
      {
        id: "vertex-location",
        label: "Location",
        component: "ElInput",
        modelPath: "location",
        defaultValue: "us-central1",
        hint: "服务所在区域，例如 us-central1",
        keywords: "location region",
      },
    ],
  },
  {
    type: "xai",
    name: "xAI (Grok)",
    description: "xAI Grok 官方服务",
    defaultBaseUrl: "https://api.x.ai/v1",
    supportsModelList: true,
    modelListEndpoint: "models",
    supportedParameters: {
      temperature: true,
      maxTokens: true,
      topP: true,
      frequencyPenalty: true,
      presencePenalty: true,
      seed: true,
      stop: true,
      responseFormat: true,
      tools: true,
      toolChoice: true,
      thinking: true,
    },
  },
  {
    type: "suno-newapi",
    name: "Suno (NewAPI)",
    description: "Suno 音乐生成服务 (基于 NewAPI/Suno-API 自创协议)",
    defaultBaseUrl: "",
    supportsModelList: false,
    supportedParameters: {},
  },
  {
    type: "minimax-music",
    name: "MiniMax Music",
    description: "MiniMax 官方音乐生成服务，支持歌曲、纯音乐、歌词生成和翻唱",
    defaultBaseUrl: "https://api.minimaxi.com",
    supportsModelList: false,
    supportedParameters: {},
  },
];

/**
 * 根据类型获取提供商信息
 */
export function getProviderTypeInfo(
  type: ProviderType
): ProviderTypeInfo | undefined {
  return providerTypes.find((p) => p.type === type);
}
