import {
  Settings2,
  Zap,
  ImageIcon,
  Headphones,
  Video,
  FileText,
} from "lucide-vue-next";
import type { SettingsSection } from "@/types/settings-renderer";
import type { TranscriptionConfig } from "./types";
import LlmModelSelector from "@/components/common/LlmModelSelector.vue";

/**
 * 默认转写配置
 */
export const DEFAULT_TRANSCRIPTION_CONFIG: TranscriptionConfig = {
  autoStartOnImport: true,
  modelIdentifier: "",
  customPrompt: "",
  temperature: 0,
  maxTokens: 4096,
  maxConcurrentTasks: 2,
  executionDelay: 500,
  maxRetries: 2,
  timeout: 300,
  enableImageSlicer: true,
  imageSlicerConfig: {
    aspectRatioThreshold: 2.0,
    blankThreshold: 0.95,
    minBlankHeight: 20,
    minCutHeight: 400,
    cutLineOffset: 5,
  },
  image: {
    modelIdentifier: "",
    customPrompt: "",
    temperature: 0,
    maxTokens: 4096,
  },
  audio: {
    modelIdentifier: "",
    customPrompt: "",
    temperature: 0,
    maxTokens: 4096,
  },
  video: {
    modelIdentifier: "",
    customPrompt: "",
    temperature: 0,
    maxTokens: 4096,
    maxDirectSizeMB: 20,
    enableCompression: true,
    maxFps: 1,
    maxResolution: 720,
  },
  document: {
    modelIdentifier: "",
    customPrompt: "",
    temperature: 0,
    maxTokens: 4096,
  },
};

export const transcriptionSettingsConfig: SettingsSection<TranscriptionConfig>[] = [
  {
    title: "基础服务配置",
    icon: Settings2,
    items: [
      {
        id: "modelIdentifier",
        label: "兜底转写模型",
        component: LlmModelSelector,
        props: {
          filterCapabilities: ["vision", "audio"],
          placeholder: "选择全局兜底多模态模型",
        },
        modelPath: "modelIdentifier",
        hint: "当具体分类（如图片、视频）未配置独立模型时，将使用此模型作为保底",
        keywords: "model default 默认 模型",
      },
      {
        id: "autoStartOnImport",
        label: "自动开始转写",
        layout: "inline",
        component: "ElSwitch",
        modelPath: "autoStartOnImport",
        hint: "文件导入资产库后立即加入转写队列",
        keywords: "auto start 自动 导入",
      },
    ],
  },
  {
    title: "性能与并发控制",
    icon: Zap,
    items: [
      {
        id: "maxConcurrentTasks",
        label: "最大并发任务数",
        component: "ElInputNumber",
        props: { min: 1, max: 15 },
        modelPath: "maxConcurrentTasks",
        hint: "",
        keywords: "concurrent task 并发 任务",
      },
      {
        id: "executionDelay",
        label: "执行延迟 (ms)",
        component: "ElInputNumber",
        props: { min: 0, step: 100 },
        modelPath: "executionDelay",
        hint: "",
        keywords: "delay 延迟",
      },
      {
        id: "maxRetries",
        label: "最大重试次数",
        component: "ElInputNumber",
        props: { min: 0, max: 5 },
        modelPath: "maxRetries",
        hint: "",
        keywords: "retry 重试",
      },
      {
        id: "timeout",
        label: "超时时间 (秒)",
        component: "ElInputNumber",
        props: { min: 30, max: 600 },
        modelPath: "timeout",
        hint: "",
        keywords: "timeout 超时",
      },
    ],
  },
  {
    title: "图片转写配置",
    icon: ImageIcon,
    items: [
      {
        id: "imageModel",
        label: "图片模型",
        component: LlmModelSelector,
        props: { filterCapabilities: ["vision"] },
        modelPath: "image.modelIdentifier",
        hint: "",
        keywords: "image model 图片 模型",
      },
      {
        id: "imagePrompt",
        label: "图片 Prompt",
        component: "ElInput",
        props: { type: "textarea", rows: 6 },
        modelPath: "image.customPrompt",
        hint: "",
        keywords: "image prompt 图片 提示词",
      },
      {
        id: "imageTemperature",
        label: "温度",
        component: "ElSlider",
        props: { min: 0, max: 1, step: 0.1 },
        modelPath: "image.temperature",
        hint: "",
        keywords: "image temperature 图片 温度",
      },
      {
        id: "imageMaxTokens",
        label: "最大 Token",
        component: "ElInputNumber",
        props: { min: 256, step: 256 },
        modelPath: "image.maxTokens",
        hint: "",
        keywords: "image max tokens 图片",
      },
      {
        id: "enableImageSlicer",
        label: "启用切片器",
        layout: "inline",
        component: "ElSwitch",
        modelPath: "enableImageSlicer",
        hint: "",
        keywords: "image slicer 切片",
      },
      {
        id: "aspectRatioThreshold",
        label: "宽高比阈值",
        component: "ElInputNumber",
        props: { min: 1, step: 0.5 },
        modelPath: "imageSlicerConfig.aspectRatioThreshold",
        hint: "",
        keywords: "aspect ratio 宽高比",
        visible: (s) => s.enableImageSlicer,
      },
      {
        id: "minCutHeight",
        label: "最小切片高度",
        component: "ElInputNumber",
        props: { min: 100, step: 100 },
        modelPath: "imageSlicerConfig.minCutHeight",
        hint: "",
        keywords: "min cut height 切片 高度",
        visible: (s) => s.enableImageSlicer,
      },
    ],
  },
  {
    title: "音频转写配置",
    icon: Headphones,
    items: [
      {
        id: "audioModel",
        label: "音频模型",
        component: LlmModelSelector,
        props: { filterCapabilities: ["audio"] },
        modelPath: "audio.modelIdentifier",
        hint: "",
        keywords: "audio model 音频 模型",
      },
      {
        id: "audioPrompt",
        label: "音频 Prompt",
        component: "ElInput",
        props: { type: "textarea", rows: 6 },
        modelPath: "audio.customPrompt",
        hint: "",
        keywords: "audio prompt 音频 提示词",
      },
      {
        id: "audioTemperature",
        label: "温度",
        component: "ElSlider",
        props: { min: 0, max: 1, step: 0.1 },
        modelPath: "audio.temperature",
        hint: "",
        keywords: "audio temperature 音频 温度",
      },
      {
        id: "audioMaxTokens",
        label: "最大 Token",
        component: "ElInputNumber",
        props: { min: 256, step: 256 },
        modelPath: "audio.maxTokens",
        hint: "",
        keywords: "audio max tokens 音频",
      },
    ],
  },
  {
    title: "视频转写配置",
    icon: Video,
    items: [
      {
        id: "videoModel",
        label: "视频模型",
        component: LlmModelSelector,
        props: { filterCapabilities: ["video", "vision"] },
        modelPath: "video.modelIdentifier",
        hint: "",
        keywords: "video model 视频 模型",
      },
      {
        id: "videoPrompt",
        label: "视频 Prompt",
        component: "ElInput",
        props: { type: "textarea", rows: 6 },
        modelPath: "video.customPrompt",
        hint: "",
        keywords: "video prompt 视频 提示词",
      },
      {
        id: "videoTemperature",
        label: "温度",
        component: "ElSlider",
        props: { min: 0, max: 1, step: 0.1 },
        modelPath: "video.temperature",
        hint: "",
        keywords: "video temperature 视频 温度",
      },
      {
        id: "videoMaxTokens",
        label: "最大 Token",
        component: "ElInputNumber",
        props: { min: 256, step: 256 },
        modelPath: "video.maxTokens",
        hint: "",
        keywords: "video max tokens 视频",
      },
      {
        id: "ffmpegPath",
        label: "FFmpeg 路径",
        component: "FileSelector",
        modelPath: "ffmpegPath",
        hint: "未配置将尝试直接上传",
        keywords: "ffmpeg path 路径",
        action: "selectFFmpegPath",
      },
      {
        id: "enableCompression",
        label: "启用视频压缩",
        layout: "inline",
        component: "ElSwitch",
        modelPath: "video.enableCompression",
        hint: "",
        keywords: "video compression 压缩",
      },
      {
        id: "maxDirectSizeMB",
        label: "体积限制 (MB)",
        component: "ElInputNumber",
        props: { min: 1, max: 100 },
        modelPath: "video.maxDirectSizeMB",
        hint: "",
        keywords: "video size 体积 限制",
      },
      {
        id: "maxFps",
        label: "最大帧率 (FPS)",
        component: "ElInputNumber",
        props: { min: 1, max: 60 },
        modelPath: "video.maxFps",
        hint: "",
        keywords: "video fps 帧率",
        visible: (s) => s.video.enableCompression,
      },
      {
        id: "maxResolution",
        label: "最大分辨率 (p)",
        component: "ElInputNumber",
        props: { min: 360, max: 2160, step: 120 },
        modelPath: "video.maxResolution",
        hint: "",
        keywords: "video resolution 分辨率",
        visible: (s) => s.video.enableCompression,
      },
    ],
  },
  {
    title: "文档转写配置",
    icon: FileText,
    items: [
      {
        id: "documentModel",
        label: "文档模型",
        component: LlmModelSelector,
        props: { filterCapabilities: ["document", "vision"] },
        modelPath: "document.modelIdentifier",
        hint: "",
        keywords: "document model 文档 模型",
      },
      {
        id: "documentPrompt",
        label: "文档 Prompt",
        component: "ElInput",
        props: { type: "textarea", rows: 6 },
        modelPath: "document.customPrompt",
        hint: "",
        keywords: "document prompt 文档 提示词",
      },
      {
        id: "documentTemperature",
        label: "温度",
        component: "ElSlider",
        props: { min: 0, max: 1, step: 0.1 },
        modelPath: "document.temperature",
        hint: "",
        keywords: "document temperature 文档 温度",
      },
      {
        id: "documentMaxTokens",
        label: "最大 Token",
        component: "ElInputNumber",
        props: { min: 256, step: 1024 },
        modelPath: "document.maxTokens",
        hint: "",
        keywords: "document max tokens 文档",
      },
    ],
  },
];