import {
  Settings2,
  Zap,
  ImageIcon,
  Headphones,
  Video,
  FileText,
} from "lucide-vue-next";
import type { SettingsSection } from "@/types/settings-renderer";
import type { TranscriptionConfig } from "./types";
import LlmModelSelector from "@/components/common/LlmModelSelector.vue";

/**
 * 默认转写配置
 */
export const DEFAULT_TRANSCRIPTION_CONFIG: TranscriptionConfig = {
  autoStartOnImport: true,
  modelIdentifier: "",
  customPrompt: "",
  temperature: 0,
  maxTokens: 4096,
  maxConcurrentTasks: 2,
  executionDelay: 500,
  maxRetries: 2,
  timeout: 300,
  enableImageSlicer: true,
  imageSlicerConfig: {
    aspectRatioThreshold: 2.0,
    blankThreshold: 0.95,
    minBlankHeight: 20,
    minCutHeight: 400,
    cutLineOffset: 5,
  },
  image: {
    modelIdentifier: "",
    customPrompt: "",
    temperature: 0,
    maxTokens: 4096,
  },
  audio: {
    modelIdentifier: "",
    customPrompt: "",
    temperature: 0,
    maxTokens: 4096,
  },
  video: {
    modelIdentifier: "",
    customPrompt: "",
    temperature: 0,
    maxTokens: 4096,
    maxDirectSizeMB: 20,
    enableCompression: true,
    maxFps: 1,
    maxResolution: 720,
  },
  document: {
    modelIdentifier: "",
    customPrompt: "",
    temperature: 0,
    maxTokens: 4096,
  },
};

export const transcriptionSettingsConfig: SettingsSection<TranscriptionConfig>[] = [
  {
    title: "基础服务配置",
    icon: Settings2,
    items: [
      {
        id: "modelIdentifier",
        label: "兜底转写模型",
        component: LlmModelSelector,
        props: {
          capabilities: { vision: true, audio: true },
          placeholder: "选择全局兜底多模态模型",
        },
        modelPath: "modelIdentifier",
        hint: "当具体分类（如图片、视频）未配置独立模型时，将使用此模型作为保底",
        keywords: "model default 默认 模型",
      },
      {
        id: "autoStartOnImport",
        label: "自动开始转写",
        layout: "inline",
        component: "ElSwitch",
        modelPath: "autoStartOnImport",
        hint: "文件导入资产库后立即加入转写队列",
        keywords: "auto start 自动 导入",
      },
    ],
  },
  {
    title: "性能与并发控制",
    icon: Zap,
    items: [
      {
        id: "maxConcurrentTasks",
        label: "最大并发任务数 ({{ localSettings.maxConcurrentTasks }})",
        component: "SliderWithInput",
        props: { min: 1, max: 15, step: 1 },
        modelPath: "maxConcurrentTasks",
        hint: "同时进行的转写任务数量",
        keywords: "concurrent task 并发 任务",
      },
      {
        id: "executionDelay",
        label: "执行延迟 ({{ localSettings.executionDelay }}ms)",
        component: "SliderWithInput",
        props: { min: 0, max: 5000, step: 100 },
        modelPath: "executionDelay",
        hint: "每个任务开始前的等待时间，用于控制请求频率",
        keywords: "delay 延迟",
      },
      {
        id: "maxRetries",
        label: "最大重试次数 ({{ localSettings.maxRetries }}次)",
        component: "SliderWithInput",
        props: { min: 0, max: 10, step: 1 },
        modelPath: "maxRetries",
        hint: "转写失败时的自动重试次数",
        keywords: "retry 重试",
      },
      {
        id: "timeout",
        label: "超时时间 ({{ localSettings.timeout }}秒)",
        component: "SliderWithInput",
        props: { min: 30, max: 600, step: 1 },
        modelPath: "timeout",
        hint: "单个转写任务的最大等待时间",
        keywords: "timeout 超时",
      },
    ],
  },
  {
    title: "图片转写配置",
    icon: ImageIcon,
    items: [
      {
        id: "imageModel",
        label: "图片模型",
        component: LlmModelSelector,
        props: { capabilities: { vision: true } },
        modelPath: "image.modelIdentifier",
        hint: "专门用于图片转写的模型。留空则使用上述兜底模型。",
        keywords: "image model 图片 模型",
      },
      {
        id: "imagePrompt",
        label: "图片 Prompt",
        component: "PromptEditor",
        props: {
          rows: 6,
          placeholder: "输入图片转写提示词",
          defaultValue: DEFAULT_TRANSCRIPTION_CONFIG.image.customPrompt,
        },
        modelPath: "image.customPrompt",
        hint: "用于指导模型如何转写图片内容",
        keywords: "image prompt 图片 提示词",
      },
      {
        id: "imageTemperature",
        label: "温度 ({{ localSettings.image.temperature }})",
        component: "SliderWithInput",
        props: { min: 0, max: 2, step: 0.1 },
        modelPath: "image.temperature",
        hint: "较低的温度会产生更确定性的转写结果",
        keywords: "image temperature 图片 温度",
      },
      {
        id: "imageMaxTokens",
        label: "最大 Token",
        component: "SliderWithInput",
        props: { min: 256, max: 32768, step: 256 },
        modelPath: "image.maxTokens",
        hint: "图片转写结果的最大 token 数",
        keywords: "image max tokens 图片",
      },
      {
        id: "enableImageSlicer",
        label: "启用切片器",
        layout: "inline",
        component: "ElSwitch",
        modelPath: "enableImageSlicer",
        hint: "",
        keywords: "image slicer 切片",
      },
      {
        id: "aspectRatioThreshold",
        label: "宽高比阈值 ({{ localSettings.imageSlicerConfig.aspectRatioThreshold }}:1)",
        component: "SliderWithInput",
        props: { min: 1, max: 10, step: 0.5 },
        modelPath: "imageSlicerConfig.aspectRatioThreshold",
        hint: "图片的长宽比超过此值时才会触发智能切图",
        keywords: "aspect ratio 宽高比",
        visible: (s) => s.enableImageSlicer,
      },
      {
        id: "minCutHeight",
        label: "最小切片高度 ({{ localSettings.imageSlicerConfig.minCutHeight }}px)",
        component: "SliderWithInput",
        props: { min: 100, max: 2000, step: 100 },
        modelPath: "imageSlicerConfig.minCutHeight",
        hint: "控制切片的最小高度，防止切图太碎",
        keywords: "min cut height 切片 高度",
        visible: (s) => s.enableImageSlicer,
      },
    ],
  },
  {
    title: "音频转写配置",
    icon: Headphones,
    items: [
      {
        id: "audioModel",
        label: "音频模型",
        component: LlmModelSelector,
        props: { capabilities: { audio: true } },
        modelPath: "audio.modelIdentifier",
        hint: "专门用于音频转写的模型。留空则使用上述兜底模型。",
        keywords: "audio model 音频 模型",
      },
      {
        id: "audioPrompt",
        label: "音频 Prompt",
        component: "PromptEditor",
        props: {
          rows: 6,
          placeholder: "输入音频转写提示词",
          defaultValue: DEFAULT_TRANSCRIPTION_CONFIG.audio.customPrompt,
        },
        modelPath: "audio.customPrompt",
        hint: "用于指导模型如何转写音频内容",
        keywords: "audio prompt 音频 提示词",
      },
      {
        id: "audioTemperature",
        label: "温度 ({{ localSettings.audio.temperature }})",
        component: "SliderWithInput",
        props: { min: 0, max: 2, step: 0.1 },
        modelPath: "audio.temperature",
        hint: "较低的温度会产生更确定性的转写结果",
        keywords: "audio temperature 音频 温度",
      },
      {
        id: "audioMaxTokens",
        label: "最大 Token",
        component: "SliderWithInput",
        props: { min: 256, max: 32768, step: 256 },
        modelPath: "audio.maxTokens",
        hint: "音频转写结果的最大 token 数",
        keywords: "audio max tokens 音频",
      },
    ],
  },
  {
    title: "视频转写配置",
    icon: Video,
    items: [
      {
        id: "videoModel",
        label: "视频模型",
        component: LlmModelSelector,
        props: { capabilities: { video: true, vision: true } },
        modelPath: "video.modelIdentifier",
        hint: "专门用于视频转写的模型。留空则使用上述兜底模型。",
        keywords: "video model 视频 模型",
      },
      {
        id: "videoPrompt",
        label: "视频 Prompt",
        component: "PromptEditor",
        props: {
          rows: 6,
          placeholder: "输入视频转写提示词",
          defaultValue: DEFAULT_TRANSCRIPTION_CONFIG.video.customPrompt,
        },
        modelPath: "video.customPrompt",
        hint: "用于指导模型如何转写视频内容",
        keywords: "video prompt 视频 提示词",
      },
      {
        id: "videoTemperature",
        label: "温度 ({{ localSettings.video.temperature }})",
        component: "SliderWithInput",
        props: { min: 0, max: 2, step: 0.1 },
        modelPath: "video.temperature",
        hint: "较低的温度会产生更确定性的转写结果",
        keywords: "video temperature 视频 温度",
      },
      {
        id: "videoMaxTokens",
        label: "最大 Token",
        component: "SliderWithInput",
        props: { min: 256, max: 32768, step: 256 },
        modelPath: "video.maxTokens",
        hint: "视频转写结果的最大 token 数",
        keywords: "video max tokens 视频",
      },
      {
        id: "ffmpegPath",
        label: "FFmpeg 路径",
        component: "FileSelector",
        modelPath: "ffmpegPath",
        hint: "未配置将尝试直接上传",
        keywords: "ffmpeg path 路径",
        action: "selectFFmpegPath",
      },
      {
        id: "enableCompression",
        label: "启用视频压缩",
        layout: "inline",
        component: "ElSwitch",
        modelPath: "video.enableCompression",
        hint: "",
        keywords: "video compression 压缩",
      },
      {
        id: "maxDirectSizeMB",
        label: "体积限制 ({{ localSettings.video.maxDirectSizeMB }}MB)",
        component: "SliderWithInput",
        props: { min: 1, max: 100, step: 1 },
        modelPath: "video.maxDirectSizeMB",
        hint: "视频体积限制，超过将尝试压缩",
        keywords: "video size 体积 限制",
      },
      {
        id: "maxFps",
        label: "最大帧率 ({{ localSettings.video.maxFps }} FPS)",
        component: "SliderWithInput",
        props: { min: 1, max: 60, step: 1 },
        modelPath: "video.maxFps",
        hint: "限制视频的最大帧率",
        keywords: "video fps 帧率",
        visible: (s) => s.video.enableCompression,
      },
      {
        id: "maxResolution",
        label: "最大分辨率 ({{ localSettings.video.maxResolution }}p)",
        component: "SliderWithInput",
        props: { min: 360, max: 2160, step: 120 },
        modelPath: "video.maxResolution",
        hint: "限制视频的最大分辨率",
        keywords: "video resolution 分辨率",
        visible: (s) => s.video.enableCompression,
      },
    ],
  },
  {
    title: "文档转写配置",
    icon: FileText,
    items: [
      {
        id: "documentModel",
        label: "文档模型",
        component: LlmModelSelector,
        props: { capabilities: { document: true, vision: true } },
        modelPath: "document.modelIdentifier",
        hint: "专门用于文档转写的模型。留空则使用上述兜底模型。",
        keywords: "document model 文档 模型",
      },
      {
        id: "documentPrompt",
        label: "文档 Prompt",
        component: "PromptEditor",
        props: {
          rows: 6,
          placeholder: "输入文档转写提示词",
          defaultValue: DEFAULT_TRANSCRIPTION_CONFIG.document.customPrompt,
        },
        modelPath: "document.customPrompt",
        hint: "用于指导模型如何解析和转录文档内容",
        keywords: "document prompt 文档 提示词",
      },
      {
        id: "documentTemperature",
        label: "温度 ({{ localSettings.document.temperature }})",
        component: "SliderWithInput",
        props: { min: 0, max: 2, step: 0.1 },
        modelPath: "document.temperature",
        hint: "较低的温度会产生更确定性的转写结果",
        keywords: "document temperature 文档 温度",
      },
      {
        id: "documentMaxTokens",
        label: "最大 Token",
        component: "SliderWithInput",
        props: { min: 256, max: 32768, step: 1024 },
        modelPath: "document.maxTokens",
        hint: "文档转写结果的最大 token 数",
        keywords: "document max tokens 文档",
      },
    ],
  },
];