/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeFormatter: typeof import('./components/CodeFormatter.vue')['default']
    CustomJsonViewer: typeof import('./components/CustomJsonViewer.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    IEpBrush: typeof import('~icons/ep/brush')['default']
    IEpCode: typeof import('~icons/ep/code')['default']
    IEpFiles: typeof import('~icons/ep/files')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpMagicStick: typeof import('~icons/ep/magic-stick')['default']
    IEpPictureFilled: typeof import('~icons/ep/picture-filled')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    InfoCard: typeof import('./components/common/InfoCard.vue')['default']
    JsonFormatter: typeof import('./components/JsonFormatter.vue')['default']
    JsonNode: typeof import('./components/JsonNode.vue')['default']
    MediaInfoReader: typeof import('./components/MediaInfoReader.vue')['default']
    RegexApplier: typeof import('./components/RegexApplier.vue')['default']
    RichCodeEditor: typeof import('./components/common/RichCodeEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextDiff: typeof import('./components/TextDiff.vue')['default']
  }
}
