/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DirectoryTreeIcon: typeof import('./components/icons/DirectoryTreeIcon.vue')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    InfoCard: typeof import('./components/common/InfoCard.vue')['default']
    RichCodeEditor: typeof import('./components/common/RichCodeEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
