name: PR 检查

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  check:
    runs-on: ubuntu-22.04
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 安装 Rust 稳定版
        uses: dtolnay/rust-toolchain@stable

      - name: 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust 缓存
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: 安装前端依赖
        run: bun install

      - name: 类型检查
        run: bun run build

      - name: Cargo 检查
        working-directory: src-tauri
        run: cargo check

      - name: Cargo 测试
        working-directory: src-tauri
        run: cargo test